apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-example
  namespace: chaos-testing
spec:
  action: loss
  mode: one
  selector:
    pods:
      test-namespace:
        - pod-name
  loss:
    loss: "100"
    correlation: "100"
  duration: "60s"
  scheduler:
    cron: "@every 10h"
