apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ""
  duration: "60s"
  selector:
    pods:
      test-namespace:
        - pod-name
  scheduler:
    cron: "@every 10h"
