apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pxc-client
  template:
    metadata:
      labels:
        name: pxc-client
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pxc-client
        command: ["bash", "-c", "sleep 100500"]
        image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/mysql/ssl
          name: ssl
      - name: backup
        command: ["bash", "-c", "sleep 100500"]
        image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup
        imagePullPolicy: Always
        command:
        - sleep
        args:
        - infinity
        volumeMounts:
        - mountPath: /etc/mysql/ssl
          name: ssl
      volumes:
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: some-name-ssl
