apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perconaxtradbbackups.pxc.percona.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.pxcCluster
      description: Cluster name
      name: Cluster
      type: string
    - JSONPath: .status.storageName
      description: Storage name from pxc spec
      name: Storage
      type: string
    - JSONPath: .status.destination
      description: Backup destination
      name: Destination
      type: string
    - JSONPath: .status.state
      description: Job status
      name: Status
      type: string
    - JSONPath: .status.completed
      description: Completed time
      name: Completed
      type: date
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: pxc.percona.com
  names:
    kind: PerconaXtraDBBackup
    listKind: PerconaXtraDBBackupList
    plural: perconaxtradbbackups
    shortNames: []
    singular: perconaxtradbbackup
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
