apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: no-proxysql
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: no-proxysql-ssl
spec:
  commonName: no-proxysql-proxysql
  dnsNames:
    - no-proxysql-pxc
    - no-proxysql-proxysql
    - '*.no-proxysql-pxc'
    - '*.no-proxysql-proxysql'
  issuerRef:
    kind: Issuer
    name: no-proxysql-pxc-issuer
  secretName: no-proxysql-ssl
