apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: no-proxysql
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: no-proxysql-pxc-issuer
spec:
  ca:
    secretName: no-proxysql-ca-cert
