apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  generation: 1
  name: no-proxysql-pxc-ca
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: no-proxysql
spec:
  selfSigned: {}
