apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  generation: 1
  name: no-proxysql-pxc-issuer
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: no-proxysql
spec:
  ca:
    secretName: no-proxysql-ca-cert
