apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations: {}
  generation: 1
  name: some-name-pxc
  ownerReferences:
    - controller: true
      kind: StatefulSet
      name: some-name-pxc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pxc
      app.kubernetes.io/instance: some-name
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
