apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/name: percona-xtradb-cluster
  name: some-name-proxysql-unready
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: some-name
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxyadm
      port: 6032
      protocol: TCP
      targetPort: 6032
    - name: mysql-admin
      port: 33062
      protocol: TCP
      targetPort: 33062
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: ClusterIP
