apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: some-name-proxysql-unready
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: some-name
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxyadm
      port: 6032
      protocol: TCP
      targetPort: 6032
    - name: mysql-admin
      port: 33062
      protocol: TCP
      targetPort: 33062
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: ClusterIP
