GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO `xtrabackup`@`%`
GRANT REPLICATION_APPLIER,SYSTEM_VARIABLES_ADMIN ON *.* TO `xtrabackup`@`%`
