apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: backup1
spec:
  pxcCluster: some-name
  storageName: s3-us-west
status:
  completed: "2020-03-12T08:27:04Z"
  destination: s3://percona-jenkins-artifactory/big-data-test/some-name-2021-02-18-12:55:09-full
  s3:
    bucket: s3://percona-jenkins-artifactory/big-data-test
    credentialsSecret: aws-s3-secret
    endpointUrl: https://s3.amazonaws.com
    region: us-west-2
  state: Succeeded
  storageName: s3-us-west
