apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: restore1
spec:
  pxcCluster: some-name
  backupSource:
    destination: s3://percona-jenkins-artifactory/big-data-test/some-name-2024-11-23-19:32:52-full
    s3:
      credentialsSecret: aws-s3-secret
      region: us-east-1
      endpointUrl: https://s3.amazonaws.com
