#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

main() {
	create_infra $namespace

	desc 'create PXC cluster with HAProxy'
	cluster="proxy-switch"
	spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml" 3 10

	desc 'check cluster is ready with HAProxy'
	wait_for_running "$cluster-pxc" 3
	wait_for_running "$cluster-haproxy" 3
	wait_cluster_consistency "$cluster" 3 3

	desc 'write data and check connectivity through HAProxy'
	run_mysql \
		'CREATE DATABASE IF NOT EXISTS myApp; use myApp; CREATE TABLE IF NOT EXISTS myApp (id int PRIMARY KEY);' \
		"-h $cluster-haproxy -uroot -proot_password"
	run_mysql \
		'INSERT myApp.myApp (id) VALUES (100500)' \
		"-h $cluster-haproxy -uroot -proot_password"
	sleep 5
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-haproxy -uroot -proot_password"

	desc 'verify data exists on all PXC nodes'
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-0.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-1.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-2.$cluster-pxc -uroot -proot_password"

	desc 'switch from HAProxy to ProxySQL'
	kubectl_bin patch pxc "$cluster" --type=json -p '[
		{"op": "replace", "path": "/spec/haproxy/enabled", "value": false},
		{"op": "replace", "path": "/spec/proxysql/enabled", "value": true}
	]'

	desc 'wait for ProxySQL to be ready and HAProxy to be removed'
	wait_for_delete "sts/$cluster-haproxy"
	wait_for_running "$cluster-proxysql" 3
	wait_cluster_consistency "$cluster" 3 3

	desc 'verify HAProxy pods are deleted'
	if kubectl_bin get pods -l "app.kubernetes.io/name=percona-xtradb-cluster,app.kubernetes.io/instance=$cluster,app.kubernetes.io/component=haproxy" 2>/dev/null | grep -q haproxy; then
		echo "HAProxy pods still exist after switching to ProxySQL"
		exit 1
	fi

	desc 'verify ProxySQL service exists'
	kubectl_bin get service "$cluster-proxysql"

	desc 'check connectivity through ProxySQL after switch'
	sleep 10
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-proxysql -uroot -proot_password"

	desc 'write new data through ProxySQL'
	run_mysql \
		'INSERT myApp.myApp (id) VALUES (100501)' \
		"-h $cluster-proxysql -uroot -proot_password"
	sleep 5
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-proxysql -uroot -proot_password"

	desc 'verify new data exists on all PXC nodes'
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-0.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-1.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-2.$cluster-pxc -uroot -proot_password"

	desc 'verify ProxySQL is routing to primary'
	initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
	if [ -z "$initial_primary" ]; then
		echo "ProxySQL primary not found"
		exit 1
	fi
	echo "ProxySQL is routing to primary: $initial_primary"

	desc 'clean up'
	destroy $namespace
	desc "test passed"
}

main