apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets-2
type: Opaque
data:
  root: cm9vdF9wYXNzd29yZA==
  xtrabackup: YmFja3VwX3Bhc3N3b3Jk
  monitor: bW9uaXRvcg==
  proxyadmin: YWRtaW5fcGFzc3dvcmQ=
  pmmserver: YWRtaW4=
