---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxc
spec:
  replicas: 1
  strategy: { type: Recreate }
  template:
    spec:
      containers:
        - name: operator
          image: pxc-operator
          env:
            - name: PXC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_PXC5.7
              value: percona/percona-xtradb-cluster:5.7.44-31.65
            - name: RELATED_IMAGE_PXC5.7-BACKUP
              value: percona/percona-xtradb-cluster-operator:1.15.0-pxc5.7-backup-pxb2.4.29
            - name: RELATED_IMAGE_PXC8.0
              value: percona/percona-xtradb-cluster:8.0.36-28.1
            - name: RELATED_IMAGE_PXC8.0-BACKUP
              value: percona/percona-xtradb-cluster-operator:1.15.0-pxc8.0-backup-pxb8.0.35
            - name: RELATED_IMAGE_HAPROXY
              value: percona/haproxy:2.8.5
            - name: RELATED_IMAGE_PROXYSQL
              value: percona/proxysql2:2.5.5
            - name: RELATED_IMAGE_LOGCOLLECTOR
              value: percona/percona-xtradb-cluster-operator:1.15.0-logcollector-fluentbit3.1.4
            - name: RELATED_IMAGE_PMMCLIENT
              value: percona/pmm-client:2.42.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      serviceAccountName: pxc
