apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: emptydir
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    volumeSpec:
      emptyDir: {}
    resources:
      requests:
        ephemeral-storage: 1G
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
    volumeSpec:
      emptyDir: {}
    resources:
      limits:
        ephemeral-storage: 1G
  pmm:
    enabled: false
