apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: hostpath
spec:
  initContainer:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    volumeSpec:
      hostPath:
        path: /run/data-dir
        type: Directory
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      supplementalGroups: [1001]
  proxysql:
    enabled: true
    size: 2
    image: -proxysql
    volumeSpec:
      hostPath:
        path: /run/proxy-dir
        type: Directory
  pmm:
    enabled: false
