#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. "${test_dir}"/../functions

set_debug

create_infra "$namespace"

desc 'create PXC cluster with 1-password secret'

newpass="test-password"
newpassencrypted=$(echo -n "$newpass" | base64)

cluster="some-name"
spinup_pxc "$cluster" "${test_dir}/conf/${cluster}.yml" "" "" "$conf_dir/secrets_one_pass.yml"

PROXYSQL_VER=$(kubectl exec -it $cluster-proxysql-0 -- sh -c 'proxysql --version 2>/dev/null' | awk '{print $3}' | cut -d. -f1)
tables_cmp_file="select-2-proxysql3"
if [[ $PROXYSQL_VER == 2 ]]; then
	tables_cmp_file="select-2"
fi

desc 'test missing passwords were created and present in internal secrets'
empty_pwds=()
wrong_pwds=()
for user in root xtrabackup monitor proxyadmin operator replication; do
	echo "Checking $user"
	secret_pass=$(getSecretData "my-cluster-secrets" "$user")
	int_secret_pass=$(getSecretData "internal-some-name" "$user")
	if [[ -z ${secret_pass} ]]; then
		empty_pwds+=("${user}")
	fi
	if [[ ${secret_pass} != "${int_secret_pass}" ]]; then
		wrong_pwds+=("${user}")
	fi
	if [[ ${user} != 'proxyadmin' ]] && ! [[ ${empty_pwds[*]} =~ ${user} ]] && ! [[ ${wrong_pwds[*]} =~ ${user} ]]; then
		echo "Running compare for ${user}"
		compare_mysql_cmd "select-4" "SHOW TABLES;" "-h ${cluster}-proxysql -u${user} -p'${secret_pass}'"
	elif [[ ${user} == 'proxyadmin' ]] && ! [[ ${empty_pwds[*]} =~ ${user} ]] && ! [[ ${wrong_pwds[*]} =~ ${user} ]]; then
		echo "Running compare for ${user}"
		compare_mysql_cmd_local "$tables_cmp_file" "SHOW TABLES;" "-h127.0.0.1 -P6032 -u${user} -p'${secret_pass}'" "${cluster}-proxysql-0" "" 'proxysql'
	fi
done
if [[ -n ${empty_pwds[*]} || -n ${wrong_pwds[*]} ]]; then
	echo "Passwords for the following users were empty: ${empty_pwds[*]:-none}"
	echo "Passwords for the following users were wrong: ${wrong_pwds[*]:-none}"
	exit 1
fi

desc 'test root'
patch_secret "my-cluster-secrets" "root" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 2
sleep 15
compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -uroot -p'$newpass'"

desc 'test proxyadmin'
kubectl_bin patch pxc some-name --type=merge -p="{\"spec\":{\"proxysql\":{\"size\":3}}}"
sleep 15
wait_cluster_consistency "$cluster" 3 3
patch_secret "my-cluster-secrets" "proxyadmin" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 3
sleep 15
compare_mysql_cmd_local "$tables_cmp_file" "SHOW TABLES;" "-h127.0.0.1 -P6032 -uproxyadmin -p'$newpass'" "$cluster-proxysql-0" "" 'proxysql'
compare_mysql_cmd_local "$tables_cmp_file" "SHOW TABLES;" "-h127.0.0.1 -P6032 -uproxyadmin -p'$newpass'" "$cluster-proxysql-1" "" 'proxysql'
compare_mysql_cmd_local "$tables_cmp_file" "SHOW TABLES;" "-h127.0.0.1 -P6032 -uproxyadmin -p'$newpass'" "$cluster-proxysql-2" "" 'proxysql'

desc 'test xtrabackup'
kubectl_bin patch pxc some-name --type=merge -p="{\"spec\":{\"proxysql\":{\"size\":2}}}"
patch_secret "my-cluster-secrets" "xtrabackup" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 2
sleep 15
compare_mysql_cmd_local "select-3" "SHOW DATABASES;" "-h 127.0.0.1 -uxtrabackup -p'$newpass'" "$cluster-pxc-0" "" 'pxc'

desc 'test monitor'
patch_secret "my-cluster-secrets" "monitor" "$newpassencrypted"
wait_for_password_propagation "my-cluster-secrets" "monitor" "$cluster"
wait_cluster_consistency "$cluster" 3 2
sleep 15 # give some time for proxy-admin --syncusers
compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -umonitor -p'$newpass'"

desc 'test operator'
patch_secret "my-cluster-secrets" "operator" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 2
sleep 15 # give some time for proxy-admin --syncusers
compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -uoperator -p'$newpass'"

desc 'change secret name'
kubectl_bin patch pxc $cluster --type merge --patch '{"spec": {"secretsName":"my-cluster-secrets-2"}}'
sleep 15
wait_cluster_consistency "$cluster" 3 2

desc 'test new operator'
newpass="test-password2"
newpassencrypted=$(echo -n "$newpass" | base64)
patch_secret "my-cluster-secrets-2" "operator" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 2

sleep 20 # give some time for proxy-admin --syncusers

compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -uoperator -p'$newpass'"

newpass=$(getSecretData "my-cluster-secrets-2" "root")
desc 'test new users sync'
run_mysql \
	"CREATE USER 'testsync'@'%' IDENTIFIED BY '$newpass';" \
	"-h $cluster-pxc -uroot -p'$newpass'"
sleep 80
compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -utestsync -p'$newpass'"

pass=$(getSecretData "internal-some-name" "operator")
desc 'check secret without operator'
kubectl_bin apply \
	-f "$test_dir/conf/secrets.yml"
sleep 60
compare_mysql_cmd "select-4" "SHOW TABLES;" "-h $cluster-proxysql -uoperator -p'$pass'"

desc 'test enable haproxy and disable proxysql '
newpass="test-password2"
newpassencrypted=$(echo -n "$newpass" | base64)
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec":{"haproxy":{"enabled":true},"proxysql":{"enabled":false},"secretsName":"my-cluster-secrets"}}'

sleep 15
wait_cluster_consistency "$cluster" 3 3
if [[ $IMAGE_PXC =~ 5\.7 ]]; then
	check_generation "2" "haproxy" "${cluster}"
else
	check_generation "1" "haproxy" "${cluster}"
fi
patch_secret "my-cluster-secrets" "monitor" "$newpassencrypted"
sleep 15
wait_cluster_consistency "$cluster" 3 3
sleep 15
compare_mysql_cmd "select-3" "SHOW DATABASES;" "-h $cluster-haproxy -umonitor -p'$newpass'"

if [[ $IMAGE_PXC =~ 5\.7 ]]; then
	check_generation "3" "haproxy" "${cluster}"
else
	check_generation "1" "haproxy" "${cluster}"
fi

destroy "${namespace}"
desc "test passed"
