apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: some-name-tls-issueref
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: some-name-tls-issueref-ssl
spec:
  commonName: some-name-tls-issueref-proxysql
  dnsNames:
    - some-name-tls-issueref-pxc
    - some-name-tls-issueref-proxysql
    - '*.some-name-tls-issueref-pxc'
    - '*.some-name-tls-issueref-proxysql'
    - test.com
  issuerRef:
    kind: ClusterIssuer
    name: special-selfsigned-issuer
  secretName: some-name-tls-issueref-ssl
