#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
cluster="monitoring"

create_infra $namespace
deploy_helm $namespace


desc 'install PMM Server'
platform=kubernetes
if [ ! -z "$OPENSHIFT" ]; then
    platform=openshift
fi
helm del monitoring || :
helm install monitoring percona/pmm-server --set platform=$platform --version 2.12.0

desc 'create PXC cluster'
spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml" 3 120

desc 'check if pmm-client container enabled'
compare_kubectl statefulset/$cluster-pxc
compare_kubectl statefulset/$cluster-haproxy

desc 'check mysql metrics'
get_metric_values node_boot_time_seconds $namespace-$cluster-pxc-0 admin:admin
get_metric_values mysql_global_status_uptime $namespace-$cluster-pxc-0 admin:admin

# TODO: check haproxy metrics

# wait for QAN
sleep 90

desc 'check QAN data'
get_qan20_values $cluster-pxc-0 admin:admin

helm delete monitoring
destroy $namespace
