#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

PXCO_FEATURE_GATES="BackupSidecar=true"

main() {
	if [ -n "$SKIP_REMOTE_BACKUPS" ]; then
		echo "Skipping test because SKIP_REMOTE_BACKUPS variable is set!"
		exit 0
	fi

	create_infra $namespace

	cluster="some-name"
	spinup_pxc "$cluster" "$conf_dir/$cluster.yml"
	keyring_plugin_must_not_be_in_use "$cluster"
	table_must_not_be_encrypted "$cluster" "myApp"

	run_backup "$cluster" "on-demand-backup-aws-s3"

	vault1="vault-service-1-${RANDOM}"
	start_vault $vault1

	run_recovery_check "$cluster" "on-demand-backup-aws-s3"
	keyring_plugin_must_be_in_use "$cluster"
	table_must_not_be_encrypted "$cluster" "myApp"

	helm uninstall $vault1 || :
	kubectl_bin delete --grace-period=0 --force=true namespace $vault1 &
	destroy $namespace
	desc "test passed"
}

main
