// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: app.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupStorageType int32

const (
	BackupStorageType_S3    BackupStorageType = 0
	BackupStorageType_AZURE BackupStorageType = 1
	BackupStorageType_GCS   BackupStorageType = 2
)

// Enum value maps for BackupStorageType.
var (
	BackupStorageType_name = map[int32]string{
		0: "S3",
		1: "AZURE",
		2: "GCS",
	}
	BackupStorageType_value = map[string]int32{
		"S3":    0,
		"AZURE": 1,
		"GCS":   2,
	}
)

func (x BackupStorageType) Enum() *BackupStorageType {
	p := new(BackupStorageType)
	*p = x
	return p
}

func (x BackupStorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupStorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_proto_enumTypes[0].Descriptor()
}

func (BackupStorageType) Type() protoreflect.EnumType {
	return &file_app_proto_enumTypes[0]
}

func (x BackupStorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupStorageType.Descriptor instead.
func (BackupStorageType) EnumDescriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

type GetCurrentBackupConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentBackupConfigRequest) Reset() {
	*x = GetCurrentBackupConfigRequest{}
	mi := &file_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentBackupConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentBackupConfigRequest) ProtoMessage() {}

func (x *GetCurrentBackupConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentBackupConfigRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentBackupConfigRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupName    string                 `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	BackupConfig  *BackupConfig          `protobuf:"bytes,2,opt,name=backup_config,json=backupConfig,proto3" json:"backup_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *CreateBackupRequest) GetBackupConfig() *BackupConfig {
	if x != nil {
		return x.BackupConfig
	}
	return nil
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupName    string                 `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	BackupConfig  *BackupConfig          `protobuf:"bytes,2,opt,name=backup_config,json=backupConfig,proto3" json:"backup_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

func (x *DeleteBackupRequest) GetBackupConfig() *BackupConfig {
	if x != nil {
		return x.BackupConfig
	}
	return nil
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{4}
}

type BackupConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Destination      string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Type             BackupStorageType      `protobuf:"varint,2,opt,name=type,proto3,enum=api.BackupStorageType" json:"type,omitempty"`
	VerifyTls        bool                   `protobuf:"varint,3,opt,name=verify_tls,json=verifyTls,proto3" json:"verify_tls,omitempty"`
	ContainerOptions *ContainerOptions      `protobuf:"bytes,4,opt,name=container_options,json=containerOptions,proto3" json:"container_options,omitempty"`
	S3               *S3Config              `protobuf:"bytes,5,opt,name=s3,proto3,oneof" json:"s3,omitempty"`
	Gcs              *GCSConfig             `protobuf:"bytes,6,opt,name=gcs,proto3,oneof" json:"gcs,omitempty"`
	Azure            *AzureConfig           `protobuf:"bytes,7,opt,name=azure,proto3,oneof" json:"azure,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackupConfig) Reset() {
	*x = BackupConfig{}
	mi := &file_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupConfig) ProtoMessage() {}

func (x *BackupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupConfig.ProtoReflect.Descriptor instead.
func (*BackupConfig) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{5}
}

func (x *BackupConfig) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *BackupConfig) GetType() BackupStorageType {
	if x != nil {
		return x.Type
	}
	return BackupStorageType_S3
}

func (x *BackupConfig) GetVerifyTls() bool {
	if x != nil {
		return x.VerifyTls
	}
	return false
}

func (x *BackupConfig) GetContainerOptions() *ContainerOptions {
	if x != nil {
		return x.ContainerOptions
	}
	return nil
}

func (x *BackupConfig) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *BackupConfig) GetGcs() *GCSConfig {
	if x != nil {
		return x.Gcs
	}
	return nil
}

func (x *BackupConfig) GetAzure() *AzureConfig {
	if x != nil {
		return x.Azure
	}
	return nil
}

type S3Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	EndpointUrl   string                 `protobuf:"bytes,3,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	AccessKey     string                 `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	StorageClass  string                 `protobuf:"bytes,6,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{6}
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Config) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *S3Config) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3Config) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *S3Config) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

type GCSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	EndpointUrl   string                 `protobuf:"bytes,2,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	StorageClass  string                 `protobuf:"bytes,3,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	AccessKey     string                 `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCSConfig) Reset() {
	*x = GCSConfig{}
	mi := &file_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSConfig) ProtoMessage() {}

func (x *GCSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSConfig.ProtoReflect.Descriptor instead.
func (*GCSConfig) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{7}
}

func (x *GCSConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GCSConfig) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *GCSConfig) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *GCSConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *GCSConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type AzureConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerName  string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	EndpointUrl    string                 `protobuf:"bytes,2,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	StorageClass   string                 `protobuf:"bytes,3,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	StorageAccount string                 `protobuf:"bytes,4,opt,name=storage_account,json=storageAccount,proto3" json:"storage_account,omitempty"`
	AccessKey      string                 `protobuf:"bytes,5,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureConfig) Reset() {
	*x = AzureConfig{}
	mi := &file_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureConfig) ProtoMessage() {}

func (x *AzureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureConfig.ProtoReflect.Descriptor instead.
func (*AzureConfig) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{8}
}

func (x *AzureConfig) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *AzureConfig) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *AzureConfig) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *AzureConfig) GetStorageAccount() string {
	if x != nil {
		return x.StorageAccount
	}
	return ""
}

func (x *AzureConfig) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{9}
}

func (x *EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BackupContainerArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xtrabackup    []string               `protobuf:"bytes,1,rep,name=xtrabackup,proto3" json:"xtrabackup,omitempty"`
	Xbcloud       []string               `protobuf:"bytes,2,rep,name=xbcloud,proto3" json:"xbcloud,omitempty"`
	Xbstream      []string               `protobuf:"bytes,3,rep,name=xbstream,proto3" json:"xbstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupContainerArgs) Reset() {
	*x = BackupContainerArgs{}
	mi := &file_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupContainerArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupContainerArgs) ProtoMessage() {}

func (x *BackupContainerArgs) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupContainerArgs.ProtoReflect.Descriptor instead.
func (*BackupContainerArgs) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{10}
}

func (x *BackupContainerArgs) GetXtrabackup() []string {
	if x != nil {
		return x.Xtrabackup
	}
	return nil
}

func (x *BackupContainerArgs) GetXbcloud() []string {
	if x != nil {
		return x.Xbcloud
	}
	return nil
}

func (x *BackupContainerArgs) GetXbstream() []string {
	if x != nil {
		return x.Xbstream
	}
	return nil
}

type ContainerOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           []*EnvVar              `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	Args          *BackupContainerArgs   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerOptions) Reset() {
	*x = ContainerOptions{}
	mi := &file_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerOptions) ProtoMessage() {}

func (x *ContainerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerOptions.ProtoReflect.Descriptor instead.
func (*ContainerOptions) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerOptions) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerOptions) GetArgs() *BackupContainerArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_app_proto protoreflect.FileDescriptor

const file_app_proto_rawDesc = "" +
	"\n" +
	"\tapp.proto\x12\x03api\"\x1f\n" +
	"\x1dGetCurrentBackupConfigRequest\"n\n" +
	"\x13CreateBackupRequest\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x126\n" +
	"\rbackup_config\x18\x02 \x01(\v2\x11.api.BackupConfigR\fbackupConfig\"\x16\n" +
	"\x14CreateBackupResponse\"n\n" +
	"\x13DeleteBackupRequest\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x126\n" +
	"\rbackup_config\x18\x02 \x01(\v2\x11.api.BackupConfigR\fbackupConfig\"\x16\n" +
	"\x14DeleteBackupResponse\"\xd0\x02\n" +
	"\fBackupConfig\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.api.BackupStorageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"verify_tls\x18\x03 \x01(\bR\tverifyTls\x12B\n" +
	"\x11container_options\x18\x04 \x01(\v2\x15.api.ContainerOptionsR\x10containerOptions\x12\"\n" +
	"\x02s3\x18\x05 \x01(\v2\r.api.S3ConfigH\x00R\x02s3\x88\x01\x01\x12%\n" +
	"\x03gcs\x18\x06 \x01(\v2\x0e.api.GCSConfigH\x01R\x03gcs\x88\x01\x01\x12+\n" +
	"\x05azure\x18\a \x01(\v2\x10.api.AzureConfigH\x02R\x05azure\x88\x01\x01B\x05\n" +
	"\x03_s3B\x06\n" +
	"\x04_gcsB\b\n" +
	"\x06_azure\"\xc0\x01\n" +
	"\bS3Config\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12!\n" +
	"\fendpoint_url\x18\x03 \x01(\tR\vendpointUrl\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\x12#\n" +
	"\rstorage_class\x18\x06 \x01(\tR\fstorageClass\"\xa9\x01\n" +
	"\tGCSConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12!\n" +
	"\fendpoint_url\x18\x02 \x01(\tR\vendpointUrl\x12#\n" +
	"\rstorage_class\x18\x03 \x01(\tR\fstorageClass\x12\x1d\n" +
	"\n" +
	"access_key\x18\x04 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\"\xc4\x01\n" +
	"\vAzureConfig\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12!\n" +
	"\fendpoint_url\x18\x02 \x01(\tR\vendpointUrl\x12#\n" +
	"\rstorage_class\x18\x03 \x01(\tR\fstorageClass\x12'\n" +
	"\x0fstorage_account\x18\x04 \x01(\tR\x0estorageAccount\x12\x1d\n" +
	"\n" +
	"access_key\x18\x05 \x01(\tR\taccessKey\"0\n" +
	"\x06EnvVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"k\n" +
	"\x13BackupContainerArgs\x12\x1e\n" +
	"\n" +
	"xtrabackup\x18\x01 \x03(\tR\n" +
	"xtrabackup\x12\x18\n" +
	"\axbcloud\x18\x02 \x03(\tR\axbcloud\x12\x1a\n" +
	"\bxbstream\x18\x03 \x03(\tR\bxbstream\"_\n" +
	"\x10ContainerOptions\x12\x1d\n" +
	"\x03env\x18\x01 \x03(\v2\v.api.EnvVarR\x03env\x12,\n" +
	"\x04args\x18\x02 \x01(\v2\x18.api.BackupContainerArgsR\x04args*/\n" +
	"\x11BackupStorageType\x12\x06\n" +
	"\x02S3\x10\x00\x12\t\n" +
	"\x05AZURE\x10\x01\x12\a\n" +
	"\x03GCS\x10\x022\xee\x01\n" +
	"\x11XtrabackupService\x12O\n" +
	"\x16GetCurrentBackupConfig\x12\".api.GetCurrentBackupConfigRequest\x1a\x11.api.BackupConfig\x12C\n" +
	"\fCreateBackup\x12\x18.api.CreateBackupRequest\x1a\x19.api.CreateBackupResponse\x12C\n" +
	"\fDeleteBackup\x12\x18.api.DeleteBackupRequest\x1a\x19.api.DeleteBackupResponseBGZEgithub.com/percona/percona-xtradb-cluster-operator/pkg/xtrabackup/apib\x06proto3"

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData []byte
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)))
	})
	return file_app_proto_rawDescData
}

var file_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_proto_goTypes = []any{
	(BackupStorageType)(0),                // 0: api.BackupStorageType
	(*GetCurrentBackupConfigRequest)(nil), // 1: api.GetCurrentBackupConfigRequest
	(*CreateBackupRequest)(nil),           // 2: api.CreateBackupRequest
	(*CreateBackupResponse)(nil),          // 3: api.CreateBackupResponse
	(*DeleteBackupRequest)(nil),           // 4: api.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),          // 5: api.DeleteBackupResponse
	(*BackupConfig)(nil),                  // 6: api.BackupConfig
	(*S3Config)(nil),                      // 7: api.S3Config
	(*GCSConfig)(nil),                     // 8: api.GCSConfig
	(*AzureConfig)(nil),                   // 9: api.AzureConfig
	(*EnvVar)(nil),                        // 10: api.EnvVar
	(*BackupContainerArgs)(nil),           // 11: api.BackupContainerArgs
	(*ContainerOptions)(nil),              // 12: api.ContainerOptions
}
var file_app_proto_depIdxs = []int32{
	6,  // 0: api.CreateBackupRequest.backup_config:type_name -> api.BackupConfig
	6,  // 1: api.DeleteBackupRequest.backup_config:type_name -> api.BackupConfig
	0,  // 2: api.BackupConfig.type:type_name -> api.BackupStorageType
	12, // 3: api.BackupConfig.container_options:type_name -> api.ContainerOptions
	7,  // 4: api.BackupConfig.s3:type_name -> api.S3Config
	8,  // 5: api.BackupConfig.gcs:type_name -> api.GCSConfig
	9,  // 6: api.BackupConfig.azure:type_name -> api.AzureConfig
	10, // 7: api.ContainerOptions.env:type_name -> api.EnvVar
	11, // 8: api.ContainerOptions.args:type_name -> api.BackupContainerArgs
	1,  // 9: api.XtrabackupService.GetCurrentBackupConfig:input_type -> api.GetCurrentBackupConfigRequest
	2,  // 10: api.XtrabackupService.CreateBackup:input_type -> api.CreateBackupRequest
	4,  // 11: api.XtrabackupService.DeleteBackup:input_type -> api.DeleteBackupRequest
	6,  // 12: api.XtrabackupService.GetCurrentBackupConfig:output_type -> api.BackupConfig
	3,  // 13: api.XtrabackupService.CreateBackup:output_type -> api.CreateBackupResponse
	5,  // 14: api.XtrabackupService.DeleteBackup:output_type -> api.DeleteBackupResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	file_app_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		EnumInfos:         file_app_proto_enumTypes,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
