// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: app.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XtrabackupService_GetCurrentBackupConfig_FullMethodName = "/api.XtrabackupService/GetCurrentBackupConfig"
	XtrabackupService_CreateBackup_FullMethodName           = "/api.XtrabackupService/CreateBackup"
	XtrabackupService_DeleteBackup_FullMethodName           = "/api.XtrabackupService/DeleteBackup"
	XtrabackupService_GetLogs_FullMethodName                = "/api.XtrabackupService/GetLogs"
)

// XtrabackupServiceClient is the client API for XtrabackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XtrabackupServiceClient interface {
	GetCurrentBackupConfig(ctx context.Context, in *GetCurrentBackupConfigRequest, opts ...grpc.CallOption) (*BackupConfig, error)
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateBackupResponse], error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type xtrabackupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXtrabackupServiceClient(cc grpc.ClientConnInterface) XtrabackupServiceClient {
	return &xtrabackupServiceClient{cc}
}

func (c *xtrabackupServiceClient) GetCurrentBackupConfig(ctx context.Context, in *GetCurrentBackupConfigRequest, opts ...grpc.CallOption) (*BackupConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupConfig)
	err := c.cc.Invoke(ctx, XtrabackupService_GetCurrentBackupConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xtrabackupServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateBackupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XtrabackupService_ServiceDesc.Streams[0], XtrabackupService_CreateBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateBackupRequest, CreateBackupResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XtrabackupService_CreateBackupClient = grpc.ServerStreamingClient[CreateBackupResponse]

func (c *xtrabackupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, XtrabackupService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xtrabackupServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XtrabackupService_ServiceDesc.Streams[1], XtrabackupService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XtrabackupService_GetLogsClient = grpc.ServerStreamingClient[LogChunk]

// XtrabackupServiceServer is the server API for XtrabackupService service.
// All implementations must embed UnimplementedXtrabackupServiceServer
// for forward compatibility.
type XtrabackupServiceServer interface {
	GetCurrentBackupConfig(context.Context, *GetCurrentBackupConfigRequest) (*BackupConfig, error)
	CreateBackup(*CreateBackupRequest, grpc.ServerStreamingServer[CreateBackupResponse]) error
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedXtrabackupServiceServer()
}

// UnimplementedXtrabackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXtrabackupServiceServer struct{}

func (UnimplementedXtrabackupServiceServer) GetCurrentBackupConfig(context.Context, *GetCurrentBackupConfigRequest) (*BackupConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentBackupConfig not implemented")
}
func (UnimplementedXtrabackupServiceServer) CreateBackup(*CreateBackupRequest, grpc.ServerStreamingServer[CreateBackupResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedXtrabackupServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedXtrabackupServiceServer) GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedXtrabackupServiceServer) mustEmbedUnimplementedXtrabackupServiceServer() {}
func (UnimplementedXtrabackupServiceServer) testEmbeddedByValue()                           {}

// UnsafeXtrabackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XtrabackupServiceServer will
// result in compilation errors.
type UnsafeXtrabackupServiceServer interface {
	mustEmbedUnimplementedXtrabackupServiceServer()
}

func RegisterXtrabackupServiceServer(s grpc.ServiceRegistrar, srv XtrabackupServiceServer) {
	// If the following call panics, it indicates UnimplementedXtrabackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XtrabackupService_ServiceDesc, srv)
}

func _XtrabackupService_GetCurrentBackupConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentBackupConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XtrabackupServiceServer).GetCurrentBackupConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XtrabackupService_GetCurrentBackupConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XtrabackupServiceServer).GetCurrentBackupConfig(ctx, req.(*GetCurrentBackupConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XtrabackupService_CreateBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateBackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XtrabackupServiceServer).CreateBackup(m, &grpc.GenericServerStream[CreateBackupRequest, CreateBackupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XtrabackupService_CreateBackupServer = grpc.ServerStreamingServer[CreateBackupResponse]

func _XtrabackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XtrabackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XtrabackupService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XtrabackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XtrabackupService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XtrabackupServiceServer).GetLogs(m, &grpc.GenericServerStream[GetLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XtrabackupService_GetLogsServer = grpc.ServerStreamingServer[LogChunk]

// XtrabackupService_ServiceDesc is the grpc.ServiceDesc for XtrabackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XtrabackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.XtrabackupService",
	HandlerType: (*XtrabackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentBackupConfig",
			Handler:    _XtrabackupService_GetCurrentBackupConfig_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _XtrabackupService_DeleteBackup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateBackup",
			Handler:       _XtrabackupService_CreateBackup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLogs",
			Handler:       _XtrabackupService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app.proto",
}
