#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

  function create_extra_pvcs() {
      local ns=$1

      echo "Creating extra PVCs in namespace ${ns}"
      kubectl_bin apply -f ${test_dir}/conf/extra-pvc.yml -n ${ns}

      echo "Waiting for source PVC to be bound"
      kubectl_bin wait --for=jsonpath='{.status.phase}'=Bound pvc/extra-storage-source -n ${ns} --timeout=60s

      echo "Waiting for populator pod to be ready"
      kubectl_bin wait --for=condition=Ready pod/pvc-populator -n ${ns} --timeout=60s
  }

function verify_extra_pvc_mounted() {
	local pod=$1
	local mount_path=$2

	echo "Verifying extra PVC is mounted in pod ${pod} at ${mount_path}"

	if ! kubectl_bin exec ${pod} -c pxc -- test -d ${mount_path}; then
		echo "Mount path ${mount_path} does not exist in pod ${pod}"
		exit 1
	fi

	echo "Mount path ${mount_path} exists in pod ${pod}"
}

function verify_extra_pvc_in_statefulset() {
	local cluster=$1
	local expected_claim_name=$2
	local expected_mount_path=$3

	echo "Verifying extra PVC configuration in StatefulSet ${cluster}-pxc"

	local volume_exists=$(kubectl_bin get statefulset ${cluster}-pxc -o json | \
		jq --arg claim "${expected_claim_name}" '.spec.template.spec.volumes[] | select(.persistentVolumeClaim.claimName == $claim) | .name' -r)

	if [[ -z "$volume_exists" ]]; then
		echo "Volume with claimName ${expected_claim_name} not found in StatefulSet"
		kubectl_bin get statefulset ${cluster}-pxc -o yaml
		exit 1
	fi

	echo "Volume ${volume_exists} with claimName ${expected_claim_name} found in StatefulSet"

	local mount_exists=$(kubectl_bin get statefulset ${cluster}-pxc -o json | \
		jq --arg path "${expected_mount_path}" '.spec.template.spec.containers[] | select(.name == "pxc") | .volumeMounts[] | select(.mountPath == $path) | .name' -r)

	if [[ -z "$mount_exists" ]]; then
		echo "Volume mount with mountPath ${expected_mount_path} not found in pxc container"
		kubectl_bin get statefulset ${cluster}-pxc -o yaml
		exit 1
	fi

	echo "Volume mount ${mount_exists} with mountPath ${expected_mount_path} found in pxc container"
}

function patch_cluster_add_extra_pvcs() {
	local cluster=$1

	echo "Patching cluster ${cluster} to add extraPVCs"

	kubectl_bin patch pxc ${cluster} --type=json -p='[
		{
			"op": "add",
			"path": "/spec/pxc/extraPVCs",
			"value": [
				{
					"name": "extra-data-volume",
					"claimName": "extra-storage-0",
					"mountPath": "/var/lib/mysql-extra",
					"readOnly": true
				}
			]
		}
	]'
}

function patch_cluster_remove_extra_pvcs() {
	local cluster=$1

	echo "Patching cluster ${cluster} to remove extraPVCs"

	kubectl_bin patch pxc ${cluster} --type=json -p='[
		{
			"op": "remove",
			"path": "/spec/pxc/extraPVCs"
		}
	]'
}

function patch_cluster_add_multiple_extra_pvcs() {
	local cluster=$1

	echo "Patching cluster ${cluster} to add multiple extraPVCs"

	kubectl_bin patch pxc ${cluster} --type=json -p='[
		{
			"op": "replace",
			"path": "/spec/pxc/extraPVCs",
			"value": [
				{
					"name": "extra-data-volume-1",
					"claimName": "extra-storage-1",
					"mountPath": "/var/lib/mysql-extra-1",
					"readOnly": true
				},
				{
					"name": "extra-data-volume-2",
					"claimName": "extra-storage-2",
					"mountPath": "/var/lib/mysql-extra-2",
					"readOnly": true
				}
			]
		}
	]'
}

set_debug

create_infra ${namespace}

desc 'create extra PVCs'
create_extra_pvcs ${namespace}

desc 'create PXC cluster without extra PVCs'
cluster="some-name"
spinup_pxc "${cluster}" "$test_dir/conf/$cluster.yml" "3" "10" "${conf_dir}/secrets.yml"

desc 'verify cluster is running without extra PVCs'
wait_cluster_consistency "$cluster" 3 2

desc 'test adding extra PVC to running cluster'
patch_cluster_add_extra_pvcs "${cluster}"
wait_cluster_consistency "$cluster" 3 2
sleep 10

desc 'verify extra PVC is configured in StatefulSet'
verify_extra_pvc_in_statefulset "${cluster}" "extra-storage-0" "/var/lib/mysql-extra"

desc 'verify extra PVC is mounted in all PXC pods'
for i in 0 1 2; do
	verify_extra_pvc_mounted "${cluster}-pxc-${i}" "/var/lib/mysql-extra"
done

desc 'test adding multiple extra PVCs'
patch_cluster_add_multiple_extra_pvcs "${cluster}"
wait_cluster_consistency "$cluster" 3 2
sleep 10

desc 'verify multiple extra PVCs are mounted'
for i in 0 1 2; do
	verify_extra_pvc_mounted "${cluster}-pxc-${i}" "/var/lib/mysql-extra-1"
	if kubectl_bin exec ${cluster}-pxc-${i} -c pxc -- touch /var/lib/mysql-extra-2/test-write 2>/dev/null; then
		echo "Read-only mount /var/lib/mysql-extra-2 is writable in pod ${cluster}-pxc-${i}"
		exit 1
	fi
	echo "Read-only mount /var/lib/mysql-extra-2 is properly read-only in pod ${cluster}-pxc-${i}"
done

desc 'test removing extra PVCs from cluster'
patch_cluster_remove_extra_pvcs "${cluster}"
wait_cluster_consistency "$cluster" 3 2
sleep 10

desc 'verify extra PVCs are removed from StatefulSet'
for claim in extra-storage-1 extra-storage-2; do
	volume_exists=$(kubectl_bin get statefulset ${cluster}-pxc -o json | \
		jq --arg claim "${claim}" '.spec.template.spec.volumes[] | select(.persistentVolumeClaim.claimName == $claim) | .name' -r)

	if [[ -n "$volume_exists" ]]; then
		echo "Volume with claimName ${claim} still exists in StatefulSet after removal"
		exit 1
	fi
done
echo "Extra PVCs successfully removed from StatefulSet"

desc 'test creating cluster with extra PVCs from start'
cluster2="some-name-2"
kubectl_bin apply -f ${test_dir}/conf/some-name-with-extra-pvcs.yml
wait_cluster_consistency "$cluster2" 3 2

desc 'verify extra PVC is configured in new cluster'
verify_extra_pvc_in_statefulset "${cluster2}" "extra-storage-0" "/var/lib/mysql-extra"

for i in 0 1 2; do
	verify_extra_pvc_mounted "${cluster2}-pxc-${i}" "/var/lib/mysql-extra"
done

desc 'cleanup second cluster'
kubectl_bin delete pxc ${cluster2}

destroy "${namespace}"
desc "test passed"