apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 2
  name: upgrade-haproxy-haproxy
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: upgrade-haproxy
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      app.kubernetes.io/instance: upgrade-haproxy
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: upgrade-haproxy-haproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: haproxy
        app.kubernetes.io/instance: upgrade-haproxy
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: haproxy
                  app.kubernetes.io/instance: upgrade-haproxy
                  app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
                  app.kubernetes.io/name: percona-xtradb-cluster
                  app.kubernetes.io/part-of: percona-xtradb-cluster
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - haproxy
          command:
            - /opt/percona/haproxy-entrypoint.sh
          env:
            - name: PXC_SERVICE
              value: upgrade-haproxy-pxc
            - name: LIVENESS_CHECK_TIMEOUT
              value: "5"
            - name: READINESS_CHECK_TIMEOUT
              value: "1"
          envFrom:
            - secretRef:
                name: upgrade-haproxy-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /opt/percona/haproxy_liveness_check.sh
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: haproxy
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 3307
              name: mysql-replicas
              protocol: TCP
            - containerPort: 3309
              name: proxy-protocol
              protocol: TCP
            - containerPort: 33062
              name: mysql-admin
              protocol: TCP
            - containerPort: 33060
              name: mysqlx
              protocol: TCP
            - containerPort: 8404
              name: stats
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /opt/percona/haproxy_readiness_check.sh
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 600m
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: upgrade-haproxy-env-vars-haproxy
        - args:
            - /opt/percona/peer-list
            - -on-change=/opt/percona/haproxy_add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
            - -protocol=$(PEER_LIST_SRV_PROTOCOL)
          command:
            - /opt/percona/haproxy-entrypoint.sh
          env:
            - name: PXC_SERVICE
              value: upgrade-haproxy-pxc
            - name: REPLICAS_SVC_ONLY_READERS
              value: "false"
            - name: HA_SERVER_OPTIONS
              value: resolvers kubernetes check inter 10000 rise 1 fall 2 weight 1
            - name: HA_SHUTDOWN_ON_MARK_DOWN
              value: "yes"
          envFrom:
            - secretRef:
                name: upgrade-haproxy-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: upgrade-haproxy-env-vars-haproxy
            - mountPath: /opt/percona
              name: bin
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /pxc-init-entrypoint.sh
          imagePullPolicy: Always
          name: pxc-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: bin
        - command:
            - /haproxy-init-entrypoint.sh
          imagePullPolicy: Always
          name: haproxy-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: upgrade-haproxy-haproxy
            optional: true
          name: haproxy-custom
        - emptyDir: {}
          name: haproxy-auto
        - name: mysql-users-secret-file
          secret:
            defaultMode: 420
            optional: false
            secretName: internal-upgrade-haproxy
        - name: upgrade-haproxy-env-vars-haproxy
          secret:
            defaultMode: 420
            optional: true
            secretName: upgrade-haproxy-env-vars-haproxy
        - emptyDir: {}
          name: bin
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
