apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: hostpath-proxysql
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: hostpath
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: proxysql
      app.kubernetes.io/instance: hostpath
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: hostpath-proxysql-unready
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxysql
        app.kubernetes.io/instance: hostpath
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: proxysql
                  app.kubernetes.io/instance: hostpath
                  app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
                  app.kubernetes.io/name: percona-xtradb-cluster
                  app.kubernetes.io/part-of: percona-xtradb-cluster
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - proxysql
            - -f
            - -c
            - /etc/proxysql/proxysql.cnf
            - --reload
          command:
            - /opt/percona/proxysql-entrypoint.sh
          env:
            - name: PXC_SERVICE
              value: hostpath-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
            - name: SCHEDULER_CHECKTIMEOUT
              value: "0"
            - name: SCHEDULER_WRITERALSOREADER
              value: "0"
            - name: SCHEDULER_RETRYUP
              value: "0"
            - name: SCHEDULER_RETRYDOWN
              value: "0"
            - name: SCHEDULER_PINGTIMEOUT
              value: "0"
            - name: SCHEDULER_NODECHECKINTERVAL
              value: "0"
            - name: SCHEDULER_MAXCONNECTIONS
              value: "0"
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 6032
              name: proxyadm
              protocol: TCP
            - containerPort: 6070
              name: stats
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/proxysql
              name: proxydata
            - mountPath: /etc/proxysql/ssl
              name: ssl
            - mountPath: /etc/proxysql/ssl-internal
              name: ssl-internal
            - mountPath: /opt/percona
              name: bin
        - args:
            - /opt/percona/peer-list
            - -on-change=/opt/percona/proxysql_add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
            - -protocol=$(PEER_LIST_SRV_PROTOCOL)
          env:
            - name: PXC_SERVICE
              value: hostpath-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/proxysql/ssl
              name: ssl
            - mountPath: /etc/proxysql/ssl-internal
              name: ssl-internal
        - args:
            - /opt/percona/peer-list
            - -on-change=/opt/percona/proxysql_add_proxysql_nodes.sh
            - -service=$(PROXYSQL_SERVICE)
            - -protocol=$(PEER_LIST_SRV_PROTOCOL)
          env:
            - name: PROXYSQL_SERVICE
              value: hostpath-proxysql-unready
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /pxc-init-entrypoint.sh
          imagePullPolicy: Always
          name: pxc-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: bin
        - command:
            - /proxysql-init-entrypoint.sh
          imagePullPolicy: Always
          name: proxysql-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /run/proxy-dir
            type: Directory
          name: proxydata
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: hostpath-ssl-internal
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: some-name-ssl
        - emptyDir: {}
          name: bin
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
