apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  name: hostpath-proxysql
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: hostpath
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: proxysql
      app.kubernetes.io/instance: hostpath
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: hostpath-proxysql-unready
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: proxysql
        app.kubernetes.io/instance: hostpath
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: proxysql
                  app.kubernetes.io/instance: hostpath
                  app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
                  app.kubernetes.io/name: percona-xtradb-cluster
                  app.kubernetes.io/part-of: percona-xtradb-cluster
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: PXC_SERVICE
              value: hostpath-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 6032
              name: proxyadm
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/proxysql
              name: proxydata
            - mountPath: /etc/proxysql/ssl
              name: ssl
            - mountPath: /etc/proxysql/ssl-internal
              name: ssl-internal
        - args:
            - /usr/bin/peer-list
            - -on-change=/usr/bin/add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
          env:
            - name: PXC_SERVICE
              value: hostpath-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - /usr/bin/peer-list
            - -on-change=/usr/bin/add_proxysql_nodes.sh
            - -service=$(PROXYSQL_SERVICE)
          env:
            - name: PROXYSQL_SERVICE
              value: hostpath-proxysql-unready
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-hostpath
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-hostpath
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-hostpath
          envFrom:
            - secretRef:
                name: hostpath-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /run/proxy-dir
            type: Directory
          name: proxydata
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: hostpath-ssl-internal
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: some-name-ssl
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
