apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: one-pod
spec:
  secretsName: my-cluster-secrets
  pause: false
  pxc:
    size: 1
    allowUnsafeConfigurations: true
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-pxc
    configuration: |
      [mysqld]
      gtid_mode=on
      enforce_gtid_consistency=on

      log-bin=binlog
      log-slave-updates

      wsrep_debug=ON
      wsrep_provider_options="gcache.size=1G; gcache.recover=yes"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  proxysql:
    enabled: false
  pmm:
    enabled: false
  backup:
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-backup
    storages:
      pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi
      aws-s3:
        type: s3
        s3:
          region: us-east-1
          bucket: operator-testing
          credentialsSecret: aws-s3-secret
