apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: proxy-protocol
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: proxy-protocol-haproxy
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: proxy-protocol
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxy-protocol
      port: 3309
      protocol: TCP
      targetPort: 3309
    - name: mysql-admin
      port: 33062
      protocol: TCP
      targetPort: 33062
    - name: mysqlx
      port: 33060
      protocol: TCP
      targetPort: 33060
  selector:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: proxy-protocol
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: LoadBalancer
