apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: side-car
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: side-car-proxysql
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: side-car
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: mysql-admin
      port: 33062
      protocol: TCP
      targetPort: 33062
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: side-car
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: LoadBalancer
