#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

cluster="some-name"

function compare_scheduler() {
	local pod=$1
	local compare_file=$2

	compare_mysql_cmd_local ${compare_file} \
		'SELECT * FROM runtime_scheduler;' \
		"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" \
		${pod}
}

function compare_proxysql_cfg() {
	local pod=$1
	local compare_file=$2

	local query='SELECT variable_value from global_variables WHERE variable_name='\'mysql-poll_timeout\'''
	compare_mysql_cmd_local ${compare_file} "${query}" \
		"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" ${pod}
}

function compare_mysql_servers() {
	local pod=$1
	local compare_file=$2

	local query='SELECT hostgroup_id,SUBSTRING(hostname, 0, 16),weight,status FROM runtime_mysql_servers WHERE status='\'ONLINE\'''

	local retry=0
	echo -n "check runtime_mysql_servers in ${pod}"
	until compare_mysql_cmd_local ${compare_file} "${query}" \
		"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" ${pod} &>/dev/null; do
		sleep 10
		echo -n .
		let retry+=1
		if [[ "$retry" -ge 30 ]]; then
			echo
			echo ""
			kubectl get pods

			if ! compare_mysql_cmd_local ${compare_file} "${query}" \
				"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" ${pod}; then
				echo
				log "max retry count (${retry}) reached.
				something went wrong with updating mysql_servers in ${pod}"
				exit 1
			fi
		fi
	done
	echo
}

# keep_pod_down repeatedly deletes a pod for as long as the given run file
# exists. The caller removes the run file to stop.
function keep_pod_down() {
	local pod=$1
	local run_file=$2

	while [[ -f ${run_file} ]]; do
		kubectl delete pod "${pod}" --ignore-not-found || true
		sleep 3
	done
}

# stop_keep_pod_down stops a keep_pod_down loop: it removes the run file (so the
# loop exits at its next iteration), then makes sure the background process is
# gone.
function stop_keep_pod_down() {
	local loop_pid=$1
	local run_file=$2

	rm -f "${run_file}"
	kill ${loop_pid} 2>/dev/null || true
	wait ${loop_pid} 2>/dev/null || true
}

create_infra ${namespace}

desc "create PXC cluster: ${cluster}"
spinup_pxc "${cluster}" "${test_dir}/conf/${cluster}.yml"
wait_cluster_consistency "${cluster}" 3 2

desc 'check proxysql custom config'
compare_proxysql_cfg "${cluster}-proxysql-0" "proxysql-cfg"

desc 'check if service and statefulset created with expected config'
compare_kubectl statefulset/${cluster}-pxc
compare_kubectl statefulset/${cluster}-proxysql
compare_kubectl service/${cluster}-pxc
compare_kubectl service/${cluster}-proxysql
compare_kubectl service/${cluster}-proxysql-unready

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

desc 'check if scheduler is enabled in all ProxySQL servers'

compare_scheduler "${cluster}-proxysql-0" "scheduler-0"
log "scheduler is enabled in ${cluster}-proxysql-0: OK"
compare_scheduler "${cluster}-proxysql-1" "scheduler-1"
log "scheduler is enabled in ${cluster}-proxysql-1: OK"

desc 'check if scheduler is doing its job in all ProxySQL servers'

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK"

desc 'check disabling scheduler'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"scheduler": {"enabled": false}}}}'
sleep_with_log 90
wait_cluster_consistency "${cluster}" 3 2
compare_scheduler "${cluster}-proxysql-0" "scheduler-0-disabled"
log "scheduler is disabled in ${cluster}-proxysql-0: OK"
compare_scheduler "${cluster}-proxysql-1" "scheduler-1-disabled"
log "scheduler is disabled in ${cluster}-proxysql-1: OK"
kubectl get pod
kubectl get pxc

desc 'check enabling scheduler'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"scheduler": {"enabled": true}}}}'
sleep_with_log 90
wait_cluster_consistency "${cluster}" 3 2
compare_scheduler "${cluster}-proxysql-0" "scheduler-0"
log "scheduler is enabled in ${cluster}-proxysql-0: OK"
compare_scheduler "${cluster}-proxysql-1" "scheduler-1"
log "scheduler is enabled in ${cluster}-proxysql-1: OK"

desc 'check PXC pod 1 is promoted to writer when pod-0 is down'

# Keep pxc-0 down for the entire duration of the checks.
# The loop runs while ${run_file} exists.
run_file=$(mktemp)
keep_pod_down "${cluster}-pxc-0" "${run_file}" &
LOOP_PID=$!
# Make sure the loop is always stopped, even if a check fails and we exit early.
trap 'stop_keep_pod_down ${LOOP_PID} "${run_file}"' EXIT

echo "LOOP_PID=$LOOP_PID"

sleep 10

log "waiting for pod0 to be removed from proxysql"
compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-pod0-down"
log "mysql_servers are configured in ${cluster}-proxysql-0 when pxc-0 is down: OK"

compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-pod0-down"
log "mysql_servers are configured in ${cluster}-proxysql-1 when pxc-0 is down: OK"

# stop the loop deleting pxc-0 (both checks passed while it was down)
stop_keep_pod_down ${LOOP_PID} "${run_file}"
trap - EXIT

wait_cluster_consistency "${cluster}" 3 2

desc 'check scaling PXC up to 5 replicas'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"size": 5}}}'
wait_pod ${cluster}-pxc-3
wait_pod ${cluster}-pxc-4

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-1"
log "new mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-1"
log "new mysql_servers are configured in ${cluster}-proxysql-1: OK"

desc 'check scaling ProxySQL up'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"size": 3}}}'
wait_pod ${cluster}-proxysql-2

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

compare_scheduler "${cluster}-proxysql-2" "scheduler-2"
log "scheduler is enabled in ${cluster}-proxysql-2: OK"

compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check writerIsAlsoReader = false'

kubectl patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"scheduler": {"writerIsAlsoReader": false}}}}'

# give some time for proxysql servers to be restarted & populated
sleep 10
wait_cluster_consistency "${cluster}" 5 3

sleep 60

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-1-writerNotReader"
log "new mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-1-writerNotReader"
log "new mysql_servers are configured in ${cluster}-proxysql-1: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-writerNotReader"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check scaling PXC down to 3 replicas'

kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"size": 3}}}'
wait_cluster_consistency "${cluster}" 3 3

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 60

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check PXC pod 0 is reader and writer when pods 1 and 2 are down'

log "scaling PXC down to 1 replica"
kubectl scale sts/${cluster}-pxc --replicas=1
sleep 20

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-two-pod-down"
log "mysql_servers are configured in ${cluster}-proxysql-0 when 2 pods are down: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-two-pod-down"
log "mysql_servers are configured in ${cluster}-proxysql-1 when 2 pods are down: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-two-pod-down"
log "mysql_servers are configured in ${cluster}-proxysql-2 when 2 pods are down: OK"

# following check is disabled because it's flaky
# and sometimes one of ProxySQL servers has a wrong weight
# for one of PXC servers... restarting that ProxySQL server
# fixes the issues ¯\_(ツ)_/¯
#
# desc 'check scaling PXC back to 3 replicas'
#
# log "scaling PXC up to 3 replicas"
# kubectl scale sts/${cluster}-pxc --replicas=3
# wait_pod ${cluster}-pxc-1
# wait_pod ${cluster}-pxc-2
# wait_cluster_consistency "${cluster}" 3 3
#
# # give some time for mysql_servers to be populated
# # this won't be needed once we add probes to ProxySQL containers
# sleep 60
#
# # check that the proxysql config is the same as before scalingdown.
# compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-scaledown"
# log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
# compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-scaledown"
# log "mysql_servers are configured in ${cluster}-proxysql-1: OK"
# compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-scaledown"
# log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc "test passed"

destroy ${namespace}
