#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

cluster="some-name"

function compare_scheduler() {
	local pod=$1
	local compare_file=$2

	compare_mysql_cmd_local ${compare_file} \
		'SELECT * FROM runtime_scheduler;' \
		"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" \
		${pod}
}

function compare_mysql_servers() {
	local pod=$1
	local compare_file=$2
	local loop_pid=$3

	retry=0
	until compare_mysql_cmd_local ${compare_file} \
		'SELECT hostgroup_id,SUBSTRING(hostname, 0, 16),weight,status FROM runtime_mysql_servers WHERE status='\'ONLINE\''' \
		"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" \
		${pod} &>/dev/null; do
		sleep 3
		echo -n .
		let retry+=1
		if [ "$retry" -ge 20 ]; then
			echo max retry count "$retry" reached. something went wrong with updating $pod.
			kill -9 $loop_pid || true
			compare_mysql_cmd_local ${compare_file} \
					'SELECT hostgroup_id,SUBSTRING(hostname, 0, 16),weight,status FROM runtime_mysql_servers WHERE status='\'ONLINE\''' \
					"-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" \
					${pod}
			exit 1
		fi
	done
}

create_infra ${namespace}

desc "create PXC cluster: ${cluster}"
spinup_pxc "${cluster}" "${test_dir}/conf/${cluster}.yml"
wait_cluster_consistency "${cluster}" 3 2

desc 'check if service and statefulset created with expected config'
compare_kubectl statefulset/${cluster}-pxc
compare_kubectl statefulset/${cluster}-proxysql
compare_kubectl service/${cluster}-pxc
compare_kubectl service/${cluster}-proxysql
compare_kubectl service/${cluster}-proxysql-unready

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

desc 'check if scheduler is enabled in all ProxySQL servers'

compare_scheduler "${cluster}-proxysql-0" "scheduler-0"
log "scheduler is enabled in ${cluster}-proxysql-0: OK"
compare_scheduler "${cluster}-proxysql-1" "scheduler-1"
log "scheduler is enabled in ${cluster}-proxysql-1: OK"

desc 'check if scheduler is doing its job in all ProxySQL servers'

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK"

desc 'check PXC pod 1 is promoted to writer when pod-0 is down'
# kill pxc pod 0 in loop
for i in {1..10}; do kubectl delete pod "${cluster}-pxc-0"; sleep 20; done &
LOOP_PID=$!

echo "LOOP_PID=$LOOP_PID"
sleep 10

desc 'check if scheduler is doing its job in all ProxySQL servers'
echo -n "waiting for pod0 to be removed from proxysql"
compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-pod0-down" $LOOP_PID
retry=0
# until compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-pod0-down" &>/dev/null; do
# 	sleep 3
# 	echo -n .
# 	let retry+=1
# 	if [ "$retry" -ge 20 ]; then
# 		echo max retry count "$retry" reached. something went wrong with updating mysql-servers after pod0 went down
# 		compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-pod0-down"
# 		kill -9 $LOOP_PID
# 		exit 1
# 	fi
# done
log "mysql_servers are configured in ${cluster}-proxysql-0: OK when pod0 is down"

# until compare_mysql_servers "${cluster}-proxysql-1"  "mysql-servers-1-pod0-down" &>/dev/null; do
# 	sleep 3
# 	echo -n .
# 	let retry+=1
# 	if [ "$retry" -ge 20 ]; then
# 		echo max retry count "$retry" reached. something went wrong with updating mysql-servers in proxysql 1 after pod0 went down
# 		compare_mysql_servers "${cluster}-proxysql-1"  "mysql-servers-1-pod0-down"
# 		kill -9 $LOOP_PID
# 		exit 1
# 	fi
# done
compare_mysql_servers "${cluster}-proxysql-1"  "mysql-servers-1-pod0-down" $LOOP_PID
log "mysql_servers are configured in ${cluster}-proxysql-1: OK when pod0 is down"

# kill process killing pxc pod 0
kill -9 $LOOP_PID

wait_cluster_consistency "${cluster}" 3 2

desc 'check scaling PXC up'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"size": 5}}}'
wait_pod ${cluster}-pxc-3
wait_pod ${cluster}-pxc-4

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-1"
log "new mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-1"
log "new mysql_servers are configured in ${cluster}-proxysql-1: OK"

desc 'check scaling ProxySQL up'
kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"size": 3}}}'
wait_pod ${cluster}-proxysql-2

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 120

compare_scheduler "${cluster}-proxysql-2" "scheduler-2"
log "scheduler is enabled in ${cluster}-proxysql-2: OK"

compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check writerIsAlsoReader = false'

kubectl patch pxc ${cluster} --type=merge -p '{"spec": {"proxysql": {"scheduler": {"writerIsAlsoReader": false}}}}'

# give some time for proxysql servers to be restarted & populated
sleep 10
wait_cluster_consistency "${cluster}" 5 3

sleep 60

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-1-writerNotReader"
log "new mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-1-writerNotReader"
log "new mysql_servers are configured in ${cluster}-proxysql-1: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-writerNotReader"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check scale down PXC'

kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"size": 3}}}'
wait_cluster_consistency "${cluster}" 3 3

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 60

compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc 'check PXC pod 0 is reader and writer when pods 1 and 2 are down'
for i in {1..10}; do kubectl delete pod "${cluster}-pxc-1"; sleep 20; done &
LOOP_PID_POD1=$!

echo "LOOP_PID_POD1=$LOOP_PID_POD1"

for i in {1..10}; do kubectl delete pod "${cluster}-pxc-2"; sleep 20; done &
LOOP_PID_POD2=$!

echo "LOOP_PID_POD2=$LOOP_PID_POD2"
sleep 10

desc 'check if scheduler is doing its job in all ProxySQL servers'
echo -n "waiting for pod1 and pod2 to be removed from proxysql"
# retry=0
# until compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-two-pod-down" &>/dev/null; do
# 	sleep 3
# 	echo -n .
# 	let retry+=1
# 	if [ "$retry" -ge 20 ]; then
# 		echo max retry count "$retry" reached. something went wrong with updating mysql-servers after pod0 went down
# 		compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-two-pod-down"
# 		kill -9 $LOOP_PID
# 		exit 1
# 	fi
# done
compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-two-pod-down" "$LOOP_PID_POD1 $LOOP_PID_POD2"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK when 2 pods are down" 
compare_mysql_servers "${cluster}-proxysql-1"  "mysql-servers-1-two-pod-down" "$LOOP_PID_POD1 $LOOP_PID_POD2"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK when 2 pods are down"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-two-pod-down" "$LOOP_PID_POD1 $LOOP_PID_POD2"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK when 2 pods are down"

kill -9 "$LOOP_PID_POD1" || true
wait_pod ${cluster}-pxc-1

kill -9 "$LOOP_PID_POD2" || true
wait_pod ${cluster}-pxc-2
# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
desc 'Check config reverted to before killing pods'
wait_cluster_consistency "${cluster}" 3 3

# give some time for mysql_servers to be populated
# this won't be needed once we add probes to ProxySQL containers
sleep 60

# check that the proxysql config is the same as before scalingdown.
compare_mysql_servers "${cluster}-proxysql-0" "mysql-servers-0-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-0: OK"
compare_mysql_servers "${cluster}-proxysql-1" "mysql-servers-1-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-1: OK"
compare_mysql_servers "${cluster}-proxysql-2" "mysql-servers-2-scaledown"
log "mysql_servers are configured in ${cluster}-proxysql-2: OK"

desc "test passed"

destroy ${namespace}

## desc set reader also writer