apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  name: some-name-tls-issue-ssl
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: some-name-tls-issue
spec:
  commonName: some-name-tls-issue-proxysql
  dnsNames:
    - some-name-tls-issue-pxc
    - '*.some-name-tls-issue-pxc'
    - '*.some-name-tls-issue-proxysql'
    - test.com
  isCA: true
  issuerRef:
    kind: Issuer
    name: some-name-tls-issue-pxc-issuer
  secretName: some-name-tls-issue-ssl
