apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: some-name-tls-issue
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: some-name-tls-issue-ssl
spec:
  commonName: some-name-tls-issue-proxysql
  dnsNames:
    - some-name-tls-issue-pxc
    - some-name-tls-issue-proxysql
    - '*.some-name-tls-issue-pxc'
    - '*.some-name-tls-issue-proxysql'
    - test.com
  duration: 1160h0m0s
  issuerRef:
    kind: Issuer
    name: some-name-tls-issue-pxc-issuer
  secretName: some-name-tls-issue-ssl
