apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: some-name-tls-issue
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: some-name-tls-issue-pxc-ca-issuer
spec:
  selfSigned: {}
