apiVersion: batch/v1
kind: Job
metadata:
  annotations: {}
  generation: 1
  labels:
    job-name: restore-job-restore-s3-sec-context
  name: restore-job-restore-s3-sec-context
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterRestore
      name: restore-s3
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels: {}
  suspend: false
  template:
    metadata:
      annotations:
        openshift.io/scc: privileged
      labels:
        job-name: restore-job-restore-s3-sec-context
    spec:
      containers:
        - command:
            - recovery-cloud.sh
          env:
            - name: ENDPOINT
              value: http://minio-service:9000/
            - name: DEFAULT_REGION
              value: us-east-1
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio-secret
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: minio-secret
            - name: PXC_SERVICE
              value: sec-context-pxc
            - name: PXC_USER
              value: xtrabackup
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "true"
            - name: XB_USE_MEMORY
              value: "750000000"
          imagePullPolicy: Always
          name: xtrabackup
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              memory: 1G
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datadir
              name: datadir
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        supplementalGroups:
          - 1001
      serviceAccount: percona-xtradb-cluster-operator-workload
      serviceAccountName: percona-xtradb-cluster-operator-workload
      terminationGracePeriodSeconds: 30
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-sec-context-pxc-0
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: sec-context-vault
