apiVersion: batch/v1
kind: Job
metadata:
  labels:
    cluster: sec-context
    job-name: sec-context-xb-on-demand-backup-s3
    type: xtrabackup
  name: sec-context-xb-on-demand-backup-s3
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBClusterBackup
    name: on-demand-backup-s3
spec:
  backoffLimit: 6
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      cluster: sec-context
      job-name: sec-context-xb-on-demand-backup-s3
      type: xtrabackup
  template:
    metadata:
      labels:
        cluster: sec-context
        job-name: sec-context-xb-on-demand-backup-s3
        type: xtrabackup
    spec:
      containers:
      - command:
        - bash
        - /usr/bin/backup.sh
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: PXC_SERVICE
          value: sec-context-pxc
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: minio-secret
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: minio-secret
        - name: DEFAULT_REGION
          value: us-east-1
        - name: ENDPOINT
          value: http://minio-service:9000/
        - name: S3_BUCKET
          value: operator-testing
        imagePullPolicy: Always
        name: xtrabackup
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
        - mountPath: /var/lib/mysql-all-keyring
          name: keyring
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 1001
        - 1002
        - 1003
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ssl
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-ssl
      - name: ssl-internal
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-ssl-internal
