apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    openshift.io/scc: privileged
  generation: 1
  labels:
    app.kubernetes.io/instance: sec-context
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
    percona.com/backup-job-name: xb-on-demand-backup-s3
    percona.com/backup-name: on-demand-backup-s3
    percona.com/backup-type: xtrabackup
    percona.com/cluster: sec-context
  name: xb-on-demand-backup-s3
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterBackup
      name: on-demand-backup-s3
spec:
  backoffLimit: 10
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sec-context
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
      percona.com/backup-job-name: xb-on-demand-backup-s3
      percona.com/backup-name: on-demand-backup-s3
      percona.com/backup-type: xtrabackup
      percona.com/cluster: sec-context
  suspend: false
  template:
    metadata:
      annotations:
        openshift.io/scc: privileged
      labels:
        app.kubernetes.io/instance: sec-context
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
        percona.com/backup-job-name: xb-on-demand-backup-s3
        percona.com/backup-name: on-demand-backup-s3
        percona.com/backup-type: xtrabackup
        percona.com/cluster: sec-context
    spec:
      containers:
        - command:
            - bash
            - /opt/percona/backup/backup.sh
          env:
            - name: BACKUP_DIR
              value: /backup
            - name: PXC_SERVICE
              value: sec-context-pxc
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "true"
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio-secret
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: minio-secret
            - name: DEFAULT_REGION
              value: us-east-1
            - name: ENDPOINT
              value: http://minio-service.namespace:9000/
            - name: S3_BUCKET
              value: operator-testing
          imagePullPolicy: Always
          name: xtrabackup
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mysql/ssl
              name: ssl
            - mountPath: /etc/mysql/ssl-internal
              name: ssl-internal
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /backup-init-entrypoint.sh
          imagePullPolicy: Always
          name: backup-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
          - 1002
          - 1003
      serviceAccount: percona-xtradb-cluster-operator-workload
      serviceAccountName: percona-xtradb-cluster-operator-workload
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: sec-context
              app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
              app.kubernetes.io/name: percona-xtradb-cluster
              app.kubernetes.io/part-of: percona-xtradb-cluster
              percona.com/backup-job-name: xb-on-demand-backup-s3
              percona.com/backup-name: on-demand-backup-s3
              percona.com/backup-type: xtrabackup
              percona.com/cluster: sec-context
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - emptyDir: {}
          name: bin
        - name: ssl
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-ssl
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-ssl-internal
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: sec-context-vault
