apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
  labels:
    name: restore-src-restore-pvc-sec-context
  name: restore-src-restore-pvc-sec-context
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterRestore
      name: restore-pvc
spec:
  containers:
    - command:
        - recovery-pvc-donor.sh
      imagePullPolicy: Always
      name: ncat
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /backup
          name: backup
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
        - mountPath: /etc/mysql/vault-keyring-secret
          name: vault-keyring-secret
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
  dnsPolicy: ClusterFirst
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    supplementalGroups:
      - 1001
      - 1002
      - 1003
  serviceAccount: percona-xtradb-cluster-operator-workload
  serviceAccountName: percona-xtradb-cluster-operator-workload
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: xb-on-demand-backup-pvc
    - name: ssl-internal
      secret:
        defaultMode: 420
        optional: true
        secretName: some-name-ssl-internal
    - name: ssl
      secret:
        defaultMode: 420
        optional: false
        secretName: some-name-ssl
    - name: vault-keyring-secret
      secret:
        defaultMode: 420
        optional: true
        secretName: sec-context-vault
    - name: kube-api-access
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
          - configMap:
              items:
                - key: service-ca.crt
                  path: service-ca.crt
              name: openshift-service-ca.crt
