apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: privileged
  labels:
    app.kubernetes.io/instance: sec-context
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
    percona.com/restore-svc-name: restore-src-restore-pvc-sec-context
  name: restore-src-restore-pvc-sec-context
  ownerReferences:
    - blockOwnerDeletion: true
      controller: true
      kind: PerconaXtraDBClusterRestore
      name: restore-pvc
spec:
  containers:
    - command:
        - /opt/percona/backup/recovery-pvc-donor.sh
      imagePullPolicy: Always
      name: ncat
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /backup
          name: backup
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
        - mountPath: /etc/mysql/vault-keyring-secret
          name: vault-keyring-secret
        - mountPath: /opt/percona
          name: bin
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
  dnsPolicy: ClusterFirst
  initContainers:
    - command:
        - /backup-init-entrypoint.sh
      imagePullPolicy: Always
      name: backup-init
      resources:
        limits:
          cpu: 50m
          memory: 50M
        requests:
          cpu: 50m
          memory: 50M
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /opt/percona
          name: bin
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    supplementalGroups:
      - 1001
      - 1002
      - 1003
  serviceAccount: percona-xtradb-cluster-operator-workload
  serviceAccountName: percona-xtradb-cluster-operator-workload
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: xb-on-demand-backup-pvc
    - name: ssl-internal
      secret:
        defaultMode: 420
        optional: true
        secretName: some-name-ssl-internal
    - name: ssl
      secret:
        defaultMode: 420
        optional: false
        secretName: some-name-ssl
    - name: vault-keyring-secret
      secret:
        defaultMode: 420
        optional: true
        secretName: sec-context-vault
    - emptyDir: {}
      name: bin
    - name: kube-api-access
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
