#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

main() {
	create_infra $namespace

	cluster="some-name"
	spinup_pxc "$cluster" "$conf_dir/$cluster.yml"
	keyring_plugin_must_not_be_in_use "$cluster"
	table_must_not_be_encrypted "$cluster" "myApp"

	vault1="vault-service-1-${RANDOM}"
	prepare_vault $vault1
	activate_vault $vault1

	run_backup "$cluster" "on-demand-backup-pvc"

	run_recovery_check "$cluster" "on-demand-backup-pvc"
	check_pvc_md5 "on-demand-backup-pvc"
	keyring_plugin_must_be_in_use "$cluster"
	table_must_not_be_encrypted "$cluster" "myApp"

	helm uninstall $vault1 || :
	kubectl_bin delete --grace-period=0 --force=true namespace $vault1 &
	destroy $namespace
	desc "test passed"
}

main
