apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  annotations:
    percona.com/unsafe-pitr: "true"
  name: restore-on-pitr-minio-gap-force
spec:
  pxcCluster: pitr-gap-errors
  backupName: on-pitr-minio-gap
  pitr:
    type: latest
    backupSource:
      storageName: "minio-binlogs"
