apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: backup-minio-source
spec:
  pxcCluster: cross-site-source
  storageName: minio
  containerOptions:
    args:
      xbstream:
      - '--parallel=2'
      xbcloud:
      - '--parallel=2'
      - '--curl-retriable-errors=8'
