apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  name: monitoring-haproxy
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: monitoring
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: monitoring-haproxy
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: haproxy
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      containers:
        - env:
            - name: PMM_SERVER
              value: monitoring-service
            - name: PMM_USER
              value: admin
            - name: PMM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pmmserver
                  name: internal-monitoring
            - name: CLIENT_PORT_LISTEN
              value: "7777"
            - name: CLIENT_PORT_MIN
              value: "30100"
            - name: CLIENT_PORT_MAX
              value: "30105"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPASE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PMM_AGENT_SERVER_ADDRESS
              value: monitoring-service
            - name: PMM_AGENT_SERVER_USERNAME
              value: admin
            - name: PMM_AGENT_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pmmserver
                  name: internal-monitoring
            - name: PMM_AGENT_LISTEN_PORT
              value: "7777"
            - name: PMM_AGENT_PORTS_MIN
              value: "30100"
            - name: PMM_AGENT_PORTS_MAX
              value: "30105"
            - name: PMM_AGENT_CONFIG_FILE
              value: /usr/local/percona/pmm2/config/pmm-agent.yaml
            - name: PMM_AGENT_SERVER_INSECURE_TLS
              value: "1"
            - name: PMM_AGENT_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: PMM_AGENT_SETUP_NODE_NAME
              value: $(POD_NAMESPASE)-$(POD_NAME)
            - name: PMM_AGENT_SETUP_METRICS_MODE
              value: push
            - name: PMM_AGENT_SETUP
              value: "1"
            - name: PMM_AGENT_SETUP_FORCE
              value: "1"
            - name: PMM_AGENT_SETUP_NODE_TYPE
              value: container
            - name: DB_TYPE
              value: haproxy
            - name: MONITOR_USER
              value: monitor
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-monitoring
            - name: DB_USER
              value: monitor
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-monitoring
            - name: DB_CLUSTER
              value: pxc
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: "3306"
            - name: CLUSTER_NAME
              value: monitoring
            - name: PMM_ADMIN_CUSTOM_PARAMS
              value: --listen-port=8404
            - name: PMM_AGENT_PRERUN_SCRIPT
              value: |-
                pmm-admin status --wait=10s;
                pmm-admin add $(DB_TYPE) $(PMM_ADMIN_CUSTOM_PARAMS) --skip-connection-check --metrics-mode=push --username=$(DB_USER) --password=$(DB_PASSWORD) --cluster=$(CLUSTER_NAME) $(PMM_AGENT_SETUP_NODE_NAME);
                pmm-admin annotate --service-name=$(PMM_AGENT_SETUP_NODE_NAME) 'Service restarted'
            - name: PMM_AGENT_SIDECAR
              value: "true"
            - name: PMM_AGENT_SIDECAR_SLEEP
              value: "5"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - pmm-admin inventory remove node --force $(pmm-admin status --json | python -c "import sys, json; print(json.load(sys.stdin)['pmm_agent_status']['node_id'])")
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /local/Status
              port: 7777
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: pmm-client
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 30100
              protocol: TCP
            - containerPort: 30101
              protocol: TCP
            - containerPort: 30102
              protocol: TCP
            - containerPort: 30103
              protocol: TCP
            - containerPort: 30104
              protocol: TCP
            - containerPort: 30105
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: 308m
              memory: 508M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
            - name: PXC_SERVICE
              value: monitoring-pxc
            - name: LIVENESS_CHECK_TIMEOUT
              value: "5"
            - name: READINESS_CHECK_TIMEOUT
              value: "1"
          envFrom:
            - secretRef:
                name: monitoring-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-check.sh
            failureThreshold: 4
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: haproxy
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 3307
              name: mysql-replicas
              protocol: TCP
            - containerPort: 3309
              name: proxy-protocol
              protocol: TCP
            - containerPort: 33062
              name: mysql-admin
              protocol: TCP
            - containerPort: 33060
              name: mysqlx
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/readiness-check.sh
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 300m
              memory: 500M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: monitoring-env-vars-haproxy
        - args:
            - /usr/bin/peer-list
            - -on-change=/usr/bin/add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
          env:
            - name: PXC_SERVICE
              value: monitoring-pxc
          envFrom:
            - secretRef:
                name: monitoring-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: monitoring-env-vars-haproxy
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: monitoring-haproxy
            optional: true
          name: haproxy-custom
        - emptyDir: {}
          name: haproxy-auto
        - name: mysql-users-secret-file
          secret:
            defaultMode: 420
            optional: false
            secretName: internal-monitoring
        - name: monitoring-env-vars-haproxy
          secret:
            defaultMode: 420
            optional: true
            secretName: monitoring-env-vars-haproxy
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
