apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <pvc-name>
spec:
  storageClassName: unsafe-flags-missing-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
