#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

if [[ $IMAGE_PXC =~ 5\.7 ]]; then
	echo "Skipping allocator test because 5.7 doesn't support it!"
	exit 0
fi

set_debug

cluster="some-name"

function check_ld_preload() {
	if ! kubectl_bin exec ${cluster}-pxc-0 -- env | grep -q LD_PRELOAD; then
		echo "LD_PRELOAD is not set!"
		exit 1
	fi

	ld_preload=$(kubectl_bin exec ${cluster}-pxc-0 -- bash -c 'echo ${LD_PRELOAD}')
	log "LD_PRELOAD is set to ${ld_preload}: OK"

	if ! kubectl_bin exec ${cluster}-pxc-0 -- ldd /usr/sbin/mysqld | grep -q ${ld_preload}; then
		echo "Allocator is not used by mysqld!"
		exit 1
	fi
	log "${ld_preload} is used by /usr/sbin/mysqld: OK"
}

function check_innodb_numa_interleave() {
	if [[ ! $IMAGE_PXC =~ 8\.4 ]]; then
		return
	fi

	compare_mysql_cmd \
		"innodb_numa_interleave" \
		"SELECT IF(@@innodb_numa_interleave, 'ON', 'OFF');" \
		"-h ${cluster}-pxc-0.${cluster}-pxc -uroot -proot_password"
	log "innodb_numa_interleave is OFF by default for MySQL 8.4: OK"
}

create_infra ${namespace}

desc "create PXC cluster: ${cluster}"
spinup_pxc "${cluster}" "${test_dir}/conf/${cluster}.yml"
wait_cluster_consistency "${cluster}" 3 2

check_innodb_numa_interleave
desc "CASE 1: Allocator is not set in cr.yaml: OK"

kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"mysqlAllocator": "tcmalloc"}}}'
sleep 7 # wait for reconciliation
wait_cluster_consistency "${cluster}" 3 2

check_ld_preload
desc "CASE 2: Allocator is set to tcmalloc: OK"

kubectl_bin patch pxc ${cluster} --type=merge -p '{"spec": {"pxc": {"mysqlAllocator": "jemalloc"}}}'
sleep 7 # wait for reconciliation
wait_cluster_consistency "${cluster}" 3 2

check_ld_preload
desc "CASE 3: Allocator is set to jemalloc: OK"

desc "test passed"

destroy ${namespace}
