#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions
cluster="no-limits"


pumba_pod() {
    local action=$1
    local pod=$(get_operator_pod)

    # run chaos for Pod
    run_pumba $action "re2:$pod"
    sleep 2

    wait_pod $pod
}

pause_pod() {
    local pod=$(get_operator_pod)

    # run chaos for Pod
    kubectl_bin exec -it "$(get_pumba)" -- /pumba -l info pause --duration 1m "re2:$pod" &
    pid=$!
    sleep 10

    desc 'check if operator works fine: scale down from 4 to 3'
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/size: 4/size: 3/' \
        | kubectl_bin apply -f-

    # wait for unpause
    wait $pid

    # check if Pod started
    wait_pod $pod

    # check scale down
    wait_for_delete pod/$cluster-pxc-3
}

netem_pod() {
    local pod=$(get_operator_pod)

    # run chaos for Pod
    kubectl_bin exec -it "$(get_pumba)" -- /pumba -l info netem --tc-image 'gaiadocker/iproute2' --duration 1m loss --percent 100 --correlation 100 "re2:$pod" &
    pid=$!
    sleep 10

    desc 'check if operator works fine: scale up from 3 to 4'
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/size: 3/size: 4/' \
        | kubectl_bin apply -f-

    # wait for unpause
    wait $pid

    # check if Pod started
    wait_pod $pod

    # check scale up
    wait_for_running "$cluster-pxc" 4
}


main() {
    create_namespace $namespace
    ## TODO: kubectl apply -f $test_dir/conf/quota.yml
    deploy_operator
    kubectl_bin apply -f "$test_dir/conf/pumba.yml"

    desc 'create PXC cluster'
    spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

    desc 'kill operator'
    pumba_pod kill
    desc 'check if operator works fine: scale up from 3 to 4'
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/size: 3/size: 4/' \
        | kubectl_bin apply -f-
    wait_for_running "$cluster-pxc" 4

    desc 'rm operator'
    pumba_pod rm
    desc 'check if operator works fine: scale down from 4 to 3'
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/size: 4/size: 3/' \
        | kubectl_bin apply -f-
    wait_for_delete pod/$cluster-pxc-3

    desc 'stop operator'
    pumba_pod stop
    desc 'check if operator works fine: scale up from 3 to 4'
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/size: 3/size: 4/' \
        | kubectl_bin apply -f-
    wait_for_running "$cluster-pxc" 4

    desc 'pause operator'
    pause_pod

    desc 'emulate bad network'
    netem_pod

    destroy $namespace
}

main
