apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations: {}
  generation: 1
  name: haproxy-haproxy
  ownerReferences:
    - controller: true
      kind: StatefulSet
      name: haproxy-haproxy
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      app.kubernetes.io/instance: haproxy
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
