apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  generation: 1
  name: haproxy-haproxy
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: haproxy
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      app.kubernetes.io/instance: haproxy
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: haproxy-haproxy
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: haproxy
        app.kubernetes.io/instance: haproxy
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: haproxy
                  app.kubernetes.io/instance: haproxy
                  app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
                  app.kubernetes.io/name: percona-xtradb-cluster
                  app.kubernetes.io/part-of: percona-xtradb-cluster
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: PXC_SERVICE
              value: haproxy-pxc
            - name: LIVENESS_CHECK_TIMEOUT
              value: "6"
            - name: READINESS_CHECK_TIMEOUT
              value: "1"
          envFrom:
            - secretRef:
                name: haproxy-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-check.sh
            failureThreshold: 5
            initialDelaySeconds: 61
            periodSeconds: 31
            successThreshold: 1
            timeoutSeconds: 6
          name: haproxy
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 3307
              name: mysql-replicas
              protocol: TCP
            - containerPort: 3309
              name: proxy-protocol
              protocol: TCP
            - containerPort: 33062
              name: mysql-admin
              protocol: TCP
            - containerPort: 33060
              name: mysqlx
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/readiness-check.sh
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: haproxy-env-vars-haproxy
        - args:
            - /usr/bin/peer-list
            - -on-change=/usr/bin/add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
          env:
            - name: PXC_SERVICE
              value: haproxy-pxc
          envFrom:
            - secretRef:
                name: haproxy-env-vars-haproxy
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/haproxy-custom/
              name: haproxy-custom
            - mountPath: /etc/haproxy/pxc
              name: haproxy-auto
            - mountPath: /etc/mysql/mysql-users-secret
              name: mysql-users-secret-file
            - mountPath: /etc/mysql/haproxy-env-secret
              name: haproxy-env-vars-haproxy
        - args:
            - -c
            - while true; do trap 'exit 0' SIGINT SIGTERM SIGQUIT SIGKILL; done;
          command:
            - /bin/sh
          imagePullPolicy: Always
          name: my-sidecar-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      runtimeClassName: docker-rc
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.alpha.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 6000
      volumes:
        - configMap:
            defaultMode: 420
            name: haproxy-haproxy
            optional: true
          name: haproxy-custom
        - emptyDir: {}
          name: haproxy-auto
        - name: mysql-users-secret-file
          secret:
            defaultMode: 420
            optional: false
            secretName: internal-haproxy
        - name: haproxy-env-vars-haproxy
          secret:
            defaultMode: 420
            optional: true
            secretName: haproxy-env-vars-haproxy
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
