apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2023-02-02T19:04:30Z"
  generation: 1
  labels:
    cluster: demand-backup-cloud
    job-name: xb-on-demand-backup-azure-blob
    type: xtrabackup
  name: xb-on-demand-backup-azure-blob
  namespace: demand-backup-cloud-10846
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBClusterBackup
    name: on-demand-backup-azure-blob
    uid: f042aed3-6f08-49cb-87ed-254a04cca61d
  resourceVersion: "150450"
  uid: 090f3426-8307-4a29-8106-20376eb5058e
spec:
  backoffLimit: 10
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      cluster: demand-backup-cloud
      job-name: xb-on-demand-backup-azure-blob
      type: xtrabackup
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        cluster: demand-backup-cloud
        job-name: xb-on-demand-backup-azure-blob
        type: xtrabackup
    spec:
      containers:
      - command:
        - bash
        - /usr/bin/backup.sh
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: PXC_SERVICE
          value: demand-backup-cloud-pxc
        - name: PXC_PASS
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: VERIFY_TLS
          value: "true"
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              key: AZURE_STORAGE_ACCOUNT_NAME
              name: azure-secret
        - name: AZURE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AZURE_STORAGE_ACCOUNT_KEY
              name: azure-secret
        - name: AZURE_CONTAINER_NAME
          value: operator-testing
        - name: AZURE_ENDPOINT
        - name: AZURE_STORAGE_CLASS
          value: Cool
        - name: BACKUP_PATH
          value: azure://operator-testing/demand-backup-cloud-2023-02-02-19:04:30-full
        image: perconalab/percona-xtradb-cluster-operator:check-pxc8.0-backup
        imagePullPolicy: Always
        name: xtrabackup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
        - mountPath: /etc/mysql/vault-keyring-secret
          name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ssl
        secret:
          defaultMode: 420
          optional: true
          secretName: demand-backup-cloud-ssl
      - name: ssl-internal
        secret:
          defaultMode: 420
          optional: true
          secretName: demand-backup-cloud-ssl-internal
      - name: vault-keyring-secret
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-vault
status:
  completionTime: "2023-02-02T19:04:58Z"
  conditions:
  - lastProbeTime: "2023-02-02T19:04:58Z"
    lastTransitionTime: "2023-02-02T19:04:58Z"
    status: "True"
    type: Complete
  startTime: "2023-02-02T19:04:30Z"
  succeeded: 1
