#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

PXCO_FEATURE_GATES="XtrabackupSidecar=true"

if [[ $IMAGE_PXC =~ 5\.7 ]]; then
	echo "Skipping PITR test because 5.7 doesn't support it!"
	exit 0
fi

run_backup() {
	local cluster=$1
	local backup=$2
	local name=$3
	if [ -z ${name} ]; then
		name=$backup
	fi

	log "run backup pxc-backup/${name}"
	cat $test_dir/conf/${backup}.yml \
		| yq eval '.metadata.name="'${name}'"' \
		| kubectl_bin apply -f -

	wait_backup $name
}

write_test_data() {
	local cluster=$1
	local size="${2:-3}"

	local proxy
	proxy=$(get_proxy "$cluster")

	desc 'write test data'
	local encrypt=''
	if [[ $IMAGE_PXC =~ 5\.7 ]] && [[ "$(is_keyring_plugin_in_use "$cluster")" ]]; then
		encrypt='ENCRYPTION=\"Y\"'
	fi
	run_mysql \
		"CREATE DATABASE IF NOT EXISTS test; use test; CREATE TABLE IF NOT EXISTS test (id int PRIMARY KEY) $encrypt;" \
		"-h $proxy -uroot -proot_password"
	run_mysql \
		'INSERT test.test (id) VALUES (100500); INSERT test.test (id) VALUES (100501); INSERT test.test (id) VALUES (100502);' \
		"-h $proxy -uroot -proot_password"
	for i in $(seq 0 $((size - 1))); do
		local node="$cluster-pxc-$i.$cluster-pxc"
		local retry=0
		until [[ "$(run_mysql 'SELECT COUNT(*) FROM test.test;' \
			"-h $node -uroot -proot_password" 2>/dev/null)" == "3" ]]; do
			[ $retry -ge 12 ] && echo "Rows not propagated to $node after 1 min" && exit 1
			sleep 5
			retry=$((retry + 1))
		done
	done
	for i in $(seq 0 $((size - 1))); do
		compare_mysql_cmd "select-2" "SELECT * from test.test;" "-h $cluster-pxc-$i.$cluster-pxc -uroot -proot_password"
	done

	if [ "$(is_keyring_plugin_in_use "$cluster")" ]; then
		table_must_be_encrypted "$cluster" "test"
	fi
}

main() {
	create_infra $namespace
	deploy_cert_manager
	kubectl_bin apply -f "$test_dir/conf/issuer.yml"
	kubectl_bin apply -f "$test_dir/conf/cert.yml"
	kubectl_bin wait certificate/tls-minio --for=condition=Ready --timeout=120s
	# We are using minio with tls enabled to check if `verifyTLS: false` works fine
	start_minio "tls-minio"

	cluster="pitr"
	mysql_root_pass=root_password
	spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

	wait_pitr_pod_ready

	run_backup "$cluster" "on-pitr-minio"

	write_test_data "$cluster"

	# test changing xtrabackup password
	desc "patching xtrabackup password"
	patch_secret "my-cluster-secrets" "xtrabackup" "$(echo -n "pass1" | base64)"
	wait_cluster_consistency ${cluster} 3 2

	desc "patching xtrabackup password"
	patch_secret "my-cluster-secrets" "xtrabackup" "$(echo -n "pass2" | base64)"
	wait_cluster_consistency ${cluster} 3 2

	desc "patching xtrabackup password"
	patch_secret "my-cluster-secrets" "xtrabackup" "$(echo -n "pass3" | base64)"
	wait_cluster_consistency ${cluster} 3 2

	compare_kubectl secret/${cluster}-mysql-init

	mysql_host="${cluster}-pxc-0.${cluster}-pxc.${namespace}"

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 1]: gtid_executed: ${gtid}"

	write_data_for_pitr "$cluster" 100503 3
	sleep_with_log 65 # wait for one binlog collection cycle

	check_binlog_collection

	check_latest_restorable_time "on-pitr-minio"
	check_binlog_gap "on-pitr-minio"

	desc "[CASE 1] PiTR with GTID: ${gtid}"
	run_recovery_check_pitr "$cluster" "restore-on-pitr-minio-gtid" "on-pitr-minio" "select-2" "" "" "$gtid"

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 1]: gtid_executed (after restore): ${gtid}"

	desc "[CASE 1] PiTR with GTID: OK"

	run_backup "$cluster" "on-pitr-minio" "on-pitr-minio-2"
	sleep_with_log 65 # wait for one binlog collection cycle

	check_binlog_gap "on-pitr-minio-2"

	time_now=$(run_mysql "SELECT now();" "-h ${mysql_host} -uroot -proot_password")

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 2]: gtid_executed: ${gtid}"

	write_data_for_pitr "$cluster" 100503 3
	sleep_with_log 65 # wait for one binlog collection cycle

	desc "[CASE 2] PiTR with datetime: ${time_now}"
	run_recovery_check_pitr "$cluster" "restore-on-pitr-minio-time" "on-pitr-minio" "select-3" "$time_now" "" ""

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 2]: gtid_executed (after restore): ${gtid}"

	desc "[CASE 2] PiTR with datetime: OK"

	run_backup "$cluster" "on-pitr-minio" "on-pitr-minio-3"
	sleep_with_log 65 # wait for one binlog collection cycle

	check_binlog_gap "on-pitr-minio-3"

	write_data_for_pitr "$cluster" 100503 3
	sleep_with_log 65 # wait for one binlog collection cycle

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 3]: gtid_executed: ${gtid}"

	dest=$(sed 's,/,\\/,g' <<<$(kubectl get pxc-backup on-pitr-minio-3 -o jsonpath='{.status.destination}'))
	desc "[CASE 3] PiTR with latest using backupSource: ${dest}"
	run_recovery_check_pitr "$cluster" "restore-on-pitr-minio" "on-pitr-minio" "select-4" "" "$dest" ""

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 3]: gtid_executed (after restore): ${gtid}"

	desc "[CASE 3] PiTR with latest using backupSource: OK"

	desc "[CASE 4] PiTR from source on new cluster"
	log "[CASE 4]: using backup destination from on-pitr-minio-3 (escaped for restore): ${dest}"

	desc "[CASE 4] delete PXC cluster ${cluster} and wait for PVCs"
	kubectl_bin delete pxc ${cluster}
	desc "[CASE 4] wait for PVCs (app.kubernetes.io/instance=${cluster}) to be deleted"
	if ! kubectl_bin wait pvc \
		-l "app.kubernetes.io/instance=${cluster}" \
		--for=delete \
		--timeout=360s; then
		if kubectl_bin get pvc -l "app.kubernetes.io/instance=${cluster}" --no-headers 2>/dev/null | grep -q .; then
			log "PVCs still exist after kubectl wait"
			kubectl_bin get pvc -l "app.kubernetes.io/instance=${cluster}"
			exit 1
		fi
	fi

	desc "[CASE 4] recreate empty PXC cluster ${cluster} with random system user passwords"
	kubectl_bin apply -f ${conf_dir}/secrets.yml
	create_random_pass "$cluster"
	apply_config "${conf_dir}/client.yml"
	apply_config "$test_dir/conf/$cluster.yml"

	proxy=$(get_proxy "$cluster")
	wait_for_running "$proxy" 2
	wait_for_running "$cluster-pxc" 3

	wait_pitr_pod_ready

	wait_cluster_consistency ${cluster} 3 2

	desc "[CASE 4] PiTR with latest using backupSource on new cluster"
	run_recovery_check_pitr "$cluster" "restore-on-pitr-minio" "on-pitr-minio" "select-4" "" "$dest" "" "$mysql_root_pass"

	gtid=$(get_gtid_executed ${mysql_host})
	log "[CASE 4]: gtid_executed (after restore): ${gtid}"

	desc "[CASE 4] PiTR from source on new cluster: OK"

	destroy $namespace
	desc "test passed"
}

main
