apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    backup-name: on-demand-backup-minio
    cluster: demand-backup
    job-name: xb-on-demand-backup-minio
    type: xtrabackup
  name: xb-on-demand-backup-minio
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterBackup
      name: on-demand-backup-minio
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      backup-name: on-demand-backup-minio
      cluster: demand-backup
      job-name: xb-on-demand-backup-minio
      type: xtrabackup
  suspend: false
  template:
    metadata:
      labels:
        backup-name: on-demand-backup-minio
        cluster: demand-backup
        job-name: xb-on-demand-backup-minio
        type: xtrabackup
    spec:
      containers:
        - command:
            - bash
            - /usr/bin/backup.sh
          env:
            - name: BACKUP_DIR
              value: /backup
            - name: PXC_SERVICE
              value: demand-backup-pxc
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "false"
            - name: XBCLOUD_EXTRA_ARGS
              value: --parallel=2 --curl-retriable-errors=8
            - name: XBSTREAM_EXTRA_ARGS
              value: --parallel=2
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio-secret
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: minio-secret
            - name: DEFAULT_REGION
              value: us-east-1
            - name: ENDPOINT
              value: https://minio-service.namespace:9000/
            - name: S3_BUCKET
              value: operator-testing
          imagePullPolicy: Always
          name: xtrabackup
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: 500m
              memory: 500M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mysql/ssl
              name: ssl
            - mountPath: /etc/mysql/ssl-internal
              name: ssl-internal
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /backup-init-entrypoint.sh
          imagePullPolicy: Always
          name: backup-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
          - 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: bin
        - name: ssl
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-ssl
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-ssl-internal
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
