apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: demand-backup
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
    percona.com/restore-job-name: restore-job-on-demand-backup-pvc-bsource-demand-backup
  name: restore-job-on-demand-backup-pvc-bsource-demand-backup
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterRestore
      name: on-demand-backup-pvc-bsource
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels: {}
  suspend: false
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demand-backup
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
        percona.com/restore-job-name: restore-job-on-demand-backup-pvc-bsource-demand-backup
    spec:
      containers:
        - command:
            - /opt/percona/backup/recovery-pvc-joiner.sh
          env:
            - name: RESTORE_SRC_SERVICE
              value: restore-src-on-demand-backup-pvc-bsource-demand-backup
            - name: XB_USE_MEMORY
              value: "750000000"
          imagePullPolicy: Always
          name: xtrabackup
          resources:
            limits:
              cpu: "2"
              memory: 1G
            requests:
              cpu: 500m
              memory: 500M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datadir
              name: datadir
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
            - mountPath: /etc/mysql/ssl
              name: ssl
            - mountPath: /etc/mysql/ssl-internal
              name: ssl-internal
            - mountPath: /opt/percona
              name: bin
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /backup-init-entrypoint.sh
          imagePullPolicy: Always
          name: backup-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-demand-backup-pxc-0
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-ssl-internal
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: demand-backup-ssl
        - emptyDir: {}
          name: bin
  ttlSecondsAfterFinished: 3600
