apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    job-name: restore-job-on-demand-backup-minio-demand-backup
  name: restore-job-on-demand-backup-minio-demand-backup
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterRestore
      name: on-demand-backup-minio
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels: {}
  suspend: false
  template:
    metadata:
      labels:
        job-name: restore-job-on-demand-backup-minio-demand-backup
    spec:
      containers:
        - command:
            - recovery-cloud.sh
          env:
            - name: PXC_SERVICE
              value: demand-backup-pxc
            - name: PXC_USER
              value: xtrabackup
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "false"
            - name: ENDPOINT
              value: https://minio-service.namespace:9000/
            - name: DEFAULT_REGION
              value: us-east-1
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio-secret
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: minio-secret
            - name: XB_EXTRA_ARGS
              value: --parallel=3
            - name: XBCLOUD_EXTRA_ARGS
              value: --parallel=3
            - name: XBSTREAM_EXTRA_ARGS
              value: --parallel=3
            - name: XB_USE_MEMORY
              value: "1500000000"
          imagePullPolicy: Always
          name: xtrabackup
          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datadir
              name: datadir
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-demand-backup-pxc-0
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
