apiVersion: pxc.percona.com/v1-10-0
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  backup:
    image: 'perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup'
    imagePullPolicy: Always
    pitr:
      enabled: false
      storageName: ''
  crVersion: 1.10.0
  enableCRValidationWebhook: false
  logCollectorSecretName: scheduled-backup-log-collector
  platform: kubernetes
  pmm: {}
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: 'perconalab/percona-xtradb-cluster-operator:main-proxysql'
    imagePullPolicy: Always
    podDisruptionBudget:
      maxUnavailable: 1
    podSecurityContext:
      fsGroup: 1001
      supplementalGroups:
        - 1001
    serviceAccountName: default
    size: 1
    sslInternalSecretName: some-name-ssl-internal
    sslSecretName: some-name-ssl
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    gracePeriod: 600
    image: 'perconalab/percona-xtradb-cluster-operator:main-pxc8.0'
    imagePullPolicy: Always
    podDisruptionBudget:
      maxUnavailable: 1
    podSecurityContext:
      fsGroup: 1001
      supplementalGroups:
        - 1001
    serviceAccountName: default
    size: 3
    sslInternalSecretName: some-name-ssl-internal
    sslSecretName: some-name-ssl
    vaultSecretName: scheduled-backup-vault
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  secretsName: my-cluster-secrets
  sslInternalSecretName: some-name-ssl-internal
  sslSecretName: some-name-ssl
  upgradeOptions: {}
