apiVersion: pxc.percona.com/v1-8-0
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.22-13.1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  proxysql:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:1.8.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  pmm:
    enabled: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.8.0-pxc8.0-backup
