apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- command: kubectl create configmap 04-mysql-compare
  namespaced: true
- script: |
    . ../helpers

    tmp_dir=$(mktemp -d)
    size=$(kubectl -n ${NAMESPACE} get pxc/$(get_cluster_name) -o jsonpath='{.spec.pxc.size}')

    for i in $(seq 0 $((size - 1))); do
        run_mysql "SELECT * from myApp.myApp;" "-h $(get_cluster_name)-pxc-$i.$(get_cluster_name)-pxc -uroot -proot_password" > "${tmp_dir}/select-1.sql"
        kubectl -n ${NAMESPACE} patch configmap 04-mysql-compare --type merge -p '{"data":{"'"$(get_cluster_name)-pxc-$i"'": "'"$(cat ${tmp_dir}/select-1.sql)"'"}}'
    done
