apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    . ../helpers

    run_mysql \
        'INSERT myApp.myApp (id) VALUES (100501)' \
        "-h $(get_proxy $(get_cluster_name)) -uroot -proot_password"

    sleep 20
    size=$(kubectl -n ${NAMESPACE} get pxc/$(get_cluster_name) -o jsonpath='{.spec.pxc.size}')
    args=''
    for i in $(seq 0 $((size - 1))); do
        run_mysql "SELECT * from myApp.myApp;" "-h $(get_cluster_name)-pxc-$i.$(get_cluster_name)-pxc -uroot -proot_password" > "${tmp_dir}/$(get_cluster_name)-pxc-$i.sql"
        args="${args} --from-file "${tmp_dir}/$(get_cluster_name)-pxc-$i.sql""
    done
    kubectl -n ${NAMESPACE} create configmap 41-mysql-compare ${args}
  timeout: 600
