#!/bin/bash

set -o errexit

test_dir="$(dirname $0)"
. $(dirname $0)/functions
src_dir="$(realpath $test_dir/..)"

$test_dir/build
create_namespace run-$GIT_BRANCH-$RANDOM
deploy_operator

desc 'create PXC cluster'
apply_cluster $src_dir/deploy/cr.yaml

wait_for_running cluster1-pxc 3
