#!/bin/bash

set -o xtrace
set -o errexit

dir=$(realpath "$(dirname "$0")")

fail() {
    local test=$1
    echo "test $test failed"
    exit 1
}

$dir/init-deploy/run || fail "init-deploy"
$dir/recreate/run || fail "recreate"
$dir/limits/run || fail "limits"
$dir/scaling/run || fail "scaling"
$dir/scaling-proxysql/run || fail "scaling-proxysql"
$dir/monitoring/run || fail "monitoring"
$dir/monitoring-2-0/run || fail "monitoring-2-0"
$dir/affinity/run || fail "affinity"
$dir/demand-backup/run || fail "demand-backup"
$dir/scheduled-backup/run || fail "scheduled-backup"
$dir/restore-to-encrypted-cluster/run || fail "restore-to-encrypted-cluster"
$dir/demand-backup-encrypted-with-tls/run || fail "demand-backup-encrypted-with-tls"
$dir/one-pod/run || fail "one-pod"
$dir/upgrade-haproxy/run || fail "upgrade-haproxy"
$dir/upgrade-proxysql/run || fail "upgrade-proxysql"
$dir/upgrade-consistency/run || fail "upgrade-consistency"
$dir/auto-tuning/run || fail "auto-tuning"
$dir/big-data/run || fail "big-data"
$dir/proxysql-sidecar-res-limits/run || fail "proxysql-sidecar-res-limits"
$dir/security-context/run || fail "security-context"
$dir/storage/run || fail "storage"
$dir/self-healing/run  || fail "self-healing"
$dir/self-healing-advanced/run || fail "self-healing-advanced"
$dir/operator-self-healing/run || fail "operator-self-healing"
$dir/users/run || fail "users"
$dir/haproxy/run || fail "haproxy"
$dir/smart-update/run || fail "smart-update"
