#!/bin/bash

set -o xtrace
set -o errexit

dir=$(realpath $(dirname $0))

$dir/init-deploy/run
$dir/recreate/run
$dir/limits/run
$dir/scaling/run
$dir/scaling-proxysql/run
$dir/monitoring/run
$dir/monitoring-2-0/run
$dir/affinity/run
$dir/demand-backup/run
$dir/scheduled-backup/run
$dir/one-pod/run
$dir/upgrade/run

$dir/storage/run
$dir/self-healing/run
$dir/self-healing-advanced/run
$dir/operator-self-healing/run
