apiVersion: v1
kind: Service
metadata:
  annotations:
    crAnnotation: "true"
    ignoredAnnotation: "true"
  labels:
    app.kubernetes.io/component: external-service
    app.kubernetes.io/instance: ignore-annotations
    app.kubernetes.io/name: percona-xtradb-cluster
    ignoredLabel: "true"
  name: ignore-annotations-pxc-0
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: ignore-annotations
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    statefulset.kubernetes.io/pod-name: ignore-annotations-pxc-0
  sessionAffinity: None
  type: ClusterIP
