apiVersion: v1
kind: Service
metadata:
  annotations:
    otherCrAnnotation: "true"
  labels:
    app.kubernetes.io/component: external-service
    app.kubernetes.io/instance: ignore-annotations
    app.kubernetes.io/name: percona-xtradb-cluster
  name: ignore-annotations-pxc-0
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: ignore-annotations
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    statefulset.kubernetes.io/pod-name: ignore-annotations-pxc-0
  sessionAffinity: None
  type: ClusterIP
