apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: no-requests-proxysql
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: no-requests
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: proxysql
      app.kubernetes.io/instance: no-requests
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: no-requests-proxysql-unready
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxysql
        app.kubernetes.io/instance: no-requests
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      containers:
        - env:
            - name: PXC_SERVICE
              value: no-requests-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-no-requests
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-no-requests
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-no-requests
            - name: SCHEDULER_CHECKTIMEOUT
              value: "0"
            - name: SCHEDULER_WRITERALSOREADER
              value: "0"
            - name: SCHEDULER_RETRYUP
              value: "0"
            - name: SCHEDULER_RETRYDOWN
              value: "0"
            - name: SCHEDULER_PINGTIMEOUT
              value: "0"
            - name: SCHEDULER_NODECHECKINTERVAL
              value: "0"
            - name: SCHEDULER_MAXCONNECTIONS
              value: "0"
            - name: PERCONA_SCHEDULER_CFG
              value: /tmp/scheduler-config.toml
          envFrom:
            - secretRef:
                name: no-requests-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            - containerPort: 6032
              name: proxyadm
              protocol: TCP
            - containerPort: 6070
              name: stats
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/proxysql
              name: proxydata
            - mountPath: /etc/proxysql/ssl
              name: ssl
            - mountPath: /etc/proxysql/ssl-internal
              name: ssl-internal
            - mountPath: /opt/percona
              name: bin
        - args:
            - /opt/percona/peer-list
            - -on-change=/opt/percona/proxysql_add_pxc_nodes.sh
            - -service=$(PXC_SERVICE)
            - -protocol=$(PEER_LIST_SRV_PROTOCOL)
          command:
            - /opt/percona/proxysql-entrypoint.sh
          env:
            - name: PXC_SERVICE
              value: no-requests-pxc
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-no-requests
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-no-requests
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-no-requests
            - name: SCHEDULER_CHECKTIMEOUT
              value: "0"
            - name: SCHEDULER_WRITERALSOREADER
              value: "0"
            - name: SCHEDULER_RETRYUP
              value: "0"
            - name: SCHEDULER_RETRYDOWN
              value: "0"
            - name: SCHEDULER_PINGTIMEOUT
              value: "0"
            - name: SCHEDULER_NODECHECKINTERVAL
              value: "0"
            - name: SCHEDULER_MAXCONNECTIONS
              value: "0"
            - name: PERCONA_SCHEDULER_CFG
              value: /tmp/scheduler-config.toml
          envFrom:
            - secretRef:
                name: no-requests-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: pxc-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
        - args:
            - /opt/percona/peer-list
            - -on-change=/opt/percona/proxysql_add_proxysql_nodes.sh
            - -service=$(PROXYSQL_SERVICE)
            - -protocol=$(PEER_LIST_SRV_PROTOCOL)
          command:
            - /opt/percona/proxysql-entrypoint.sh
          env:
            - name: PROXYSQL_SERVICE
              value: no-requests-proxysql-unready
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: operator
                  name: internal-no-requests
            - name: PROXY_ADMIN_USER
              value: proxyadmin
            - name: PROXY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: proxyadmin
                  name: internal-no-requests
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: monitor
                  name: internal-no-requests
          envFrom:
            - secretRef:
                name: no-requests-env-vars-proxysql
                optional: true
          imagePullPolicy: Always
          name: proxysql-monit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /pxc-init-entrypoint.sh
          imagePullPolicy: Always
          name: pxc-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: bin
        - command:
            - /proxysql-init-entrypoint.sh
          imagePullPolicy: Always
          name: proxysql-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-ssl-internal
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: some-name-ssl
        - emptyDir: {}
          name: bin
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/component: proxysql
          app.kubernetes.io/instance: no-requests
          app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
          app.kubernetes.io/name: percona-xtradb-cluster
          app.kubernetes.io/part-of: percona-xtradb-cluster
        name: proxydata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 6Gi
      status:
        phase: Pending
