apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 2
  name: no-limits-pxc
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-limits
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: pxc
      app.kubernetes.io/instance: no-limits
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: no-limits-pxc
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: pxc
        app.kubernetes.io/instance: no-limits
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      containers:
      - args:
        - mysqld
        command:
        - /var/lib/mysql/pxc-entrypoint.sh
        env:
        - name: PXC_SERVICE
          value: no-limits-pxc-unready
        - name: MONITOR_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        - name: CLUSTERCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: clustercheck
              name: my-cluster-secrets
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: pxc
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 4444
          name: sst
          protocol: TCP
        - containerPort: 4567
          name: write-set
          protocol: TCP
        - containerPort: 4568
          name: ist
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 600m
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/percona-xtradb-cluster.conf.d
          name: config
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
        - mountPath: /etc/my.cnf.d
          name: auto-config
        - mountPath: /etc/mysql/vault-keyring-secret
          name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /pxc-init-entrypoint.sh
        imagePullPolicy: IfNotPresent
        name: pxc-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datadir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 1001
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: tmp
      - configMap:
          defaultMode: 420
          name: no-limits-pxc
          optional: true
        name: config
      - name: ssl-internal
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-ssl-internal
      - name: ssl
        secret:
          defaultMode: 420
          optional: false
          secretName: some-name-ssl
      - configMap:
          defaultMode: 420
          name: auto-no-limits-pxc
          optional: true
        name: auto-config
      - name: vault-keyring-secret
        secret:
          defaultMode: 420
          optional: true
          secretName: no-limits-vault
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 6Gi
    status:
      phase: Pending
