apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: some-name
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  unsafeFlags:
    pxcSize: true
  pxc:
    size: 3
    sstRetryCount: 2
    image: -pxc
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 300M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: false
  pmm:
    enabled: false
