#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

cluster='some-name'

wait_for_sts_generation() {
	local name="$1"
	local desired_generation="$2"
	local size="$3"
	set +o xtrace
	echo -n "Waiting for statefulset readyness"
	retry=0
	until [[ "$(kubectl_bin get sts $name -o jsonpath='{.status.observedGeneration}')" == "$desired_generation" &&
	"$(kubectl_bin get sts $name -o jsonpath='{.status.readyReplicas}')" -ge $size ]]; do
		sleep 1
		echo -n .
		let retry+=1
		if [ $retry -ge 300 ]; then
			kubectl_bin logs $(get_operator_pod) ${OPERATOR_NS:+-n $OPERATOR_NS}
			echo max retry count $retry reached. Desired STS generation $desired_generation not found OR readyReplicas is less than $size
			exit 1
		fi
	done
	echo
	set -o xtrace
}

main() {
	create_infra $namespace

	apply_config "$conf_dir/client.yml"
	kubectl_bin apply \
		-f "$test_dir/conf/secrets.yml"
	cat_config "$conf_dir/$cluster.yml" \
		| yq eval '.spec.crVersion = "1.13.0"' - \
		| kubectl_bin apply -f -

	desc "test 1.13.0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.13.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "1" "1"
	desc "compare k8s objects"
	compare_kubectl service/$cluster-pxc "-1130"
	compare_kubectl service/$cluster-proxysql "-1130"
	compare_kubectl statefulset/$cluster-pxc "-1130"
	compare_kubectl statefulset/$cluster-proxysql "-1130"

	desc "test 1.14.0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.14.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "2" "1"
	desc "compare k8s objects"
	compare_kubectl service/$cluster-pxc "-1140"
	compare_kubectl service/$cluster-proxysql "-1140"
	compare_kubectl statefulset/$cluster-pxc "-1140"
	compare_kubectl statefulset/$cluster-proxysql "-1140"

	desc "test 1.15.0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.15.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "3" "1"
	desc "compare k8s objects"
	compare_kubectl service/$cluster-pxc "-1150"
	compare_kubectl service/$cluster-proxysql "-1150"
	compare_kubectl statefulset/$cluster-pxc "-1150"
	compare_kubectl statefulset/$cluster-proxysql "-1150"

	destroy "${namespace}"
	desc "test passed"
}

main
