#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

cluster='some-name'

wait_for_sts_generation() {
	local name="${1}"
	local desired_generation="${2}"
	local size="${3}"
	set +o xtrace
	echo -n "Waiting for statefulset readyness"
	retry=0
	until [[ "$(kubectl_bin get sts $name -o jsonpath='{.status.observedGeneration}')" == "${desired_generation}" &&
	"$(kubectl_bin get sts $name -o jsonpath='{.status.readyReplicas}')" -ge ${size} ]]; do
		sleep 1
		echo -n .
		let retry+=1
		if [ $retry -ge 300 ]; then
			kubectl_bin logs $(get_operator_pod) ${OPERATOR_NS:+-n $OPERATOR_NS}
			echo max retry count $retry reached. something went wrong with operator or kubernetes cluster
			exit 1
		fi
	done
	echo
	set -o xtrace
}

main() {
	create_infra $namespace

	apply_config "$conf_dir/client.yml"
	kubectl_bin apply \
		-f "$test_dir/conf/secrets.yml"

	# test 1.8.0
	API="pxc.percona.com/v1-8-0"
	apply_config "$conf_dir/$cluster.yml"
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "1" "1"
	compare_kubectl service/$cluster-pxc "-180"
	compare_kubectl service/$cluster-proxysql "-180"
	compare_kubectl statefulset/$cluster-pxc "-180"
	compare_kubectl statefulset/$cluster-proxysql "-180"

	# test 1.9.0
	API="pxc.percona.com/v1-9-0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.9.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "2" "1"
	compare_kubectl service/$cluster-pxc "-190"
	compare_kubectl service/$cluster-proxysql "-190"
	compare_kubectl statefulset/$cluster-pxc "-190"
	compare_kubectl statefulset/$cluster-proxysql "-190"

	# test 1.10.0
	API="pxc.percona.com/v1-10-0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.10.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "3" "1"
	compare_kubectl service/$cluster-pxc "-1100"
	compare_kubectl service/$cluster-proxysql "-1100"
	compare_kubectl statefulset/$cluster-pxc "-1100"
	compare_kubectl statefulset/$cluster-proxysql "-1100"

	# test 1.11.0
	API="pxc.percona.com/v1-11-0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.11.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "4" "1"
	compare_kubectl service/$cluster-pxc "-1110"
	compare_kubectl service/$cluster-proxysql "-1110"
	compare_kubectl statefulset/$cluster-pxc "-1110"
	compare_kubectl statefulset/$cluster-proxysql "-1110"

	# test 1.12.0
	API="pxc.percona.com/v1-12-0"
	kubectl_bin patch pxc "$cluster" --type=merge --patch '{
        "spec": {"crVersion":"1.12.0"}
    }'
	wait_cluster_consistency "$cluster" 3 2
	wait_for_sts_generation "$cluster-pxc" "5" "1"
	compare_kubectl service/$cluster-pxc "-1120"
	compare_kubectl service/$cluster-proxysql "-1120"
	compare_kubectl statefulset/$cluster-pxc "-1120"
	compare_kubectl statefulset/$cluster-proxysql "-1120"

	destroy "${namespace}"
}

main
