apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: smart-update
  finalizers:
    - percona.com/delete-pxc-pods-in-order
spec:
  crVersion: 9.9.9
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://127.0.0.1/versions
    apply: recommended
    schedule: "0 4 * * *"
  secretsName: my-cluster-secrets
  pause: false
  pxc:
    size: 3
    image: -pxc
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  proxysql:
    enabled: false
    size: 2
    image: -proxysql
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  haproxy:
    enabled: true
    size: 2
    image: -haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  pmm:
    enabled: false
    image: percona/pmm-client:2.44.0
    serverHost: monitoring-service
    serverUser: pmm
  backup:
    image: -backup
    serviceAccountName: percona-xtradb-cluster-operator
    storages:
      pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 2Gi
