#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions


main() {
    create_namespace $namespace
    deploy_cert_manager
    deploy_operator

    desc 'create first PXC cluster'
    cluster="some-name"
    spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

    kubectl_bin apply -f "${conf_dir}/cloud-secret.yml" 

    kubectl_bin apply -f "${test_dir}/conf/crd_backup.yml"
    kubectl_bin apply -f "${test_dir}/conf/backup.yml"
    sleep 10

    kubectl_bin apply -f "${test_dir}/conf/restore-backup.yml"

    wait_backup_restore "restore1"

    wait_for_running "$cluster-proxysql" 1
    wait_for_running "$cluster-pxc" 3
    
    kubectl_bin delete pod/"$cluster-pxc-2" pvc/"datadir-$cluster-pxc-2"

    wait_for_running "$cluster-pxc" 3
    destroy $namespace
}

main
