apiVersion: pxc.percona.com/v1-6-0
kind: PerconaXtraDBCluster
metadata:
  name: scaling
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    size: 3
    image: -pxc
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
