#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_infra $namespace
deploy_cert_manager

desc 'create PXC cluster'
cluster="side-car"
spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml" "3" "10" "${conf_dir}/secrets_without_tls.yml"

desc 'check if service and statefulset created with expected config'
compare_kubectl service/$cluster-proxysql
compare_kubectl statefulset/$cluster-proxysql

destroy $namespace
