#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

create_namespace $namespace
deploy_cert_manager
deploy_operator

desc 'create PXC cluster'
cluster="side-car"
spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

desc 'check if service and statefulset created with expected config'
compare_kubectl statefulset/$cluster-proxysql

destroy $namespace
