// Code generated by go-swagger; DO NOT EDIT.

package version_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/percona/percona-xtradb-cluster-operator/pkg/version/client/models"
)

// VersionServiceGetReleaseNotesReader is a Reader for the VersionServiceGetReleaseNotes structure.
type VersionServiceGetReleaseNotesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionServiceGetReleaseNotesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVersionServiceGetReleaseNotesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVersionServiceGetReleaseNotesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVersionServiceGetReleaseNotesOK creates a VersionServiceGetReleaseNotesOK with default headers values
func NewVersionServiceGetReleaseNotesOK() *VersionServiceGetReleaseNotesOK {
	return &VersionServiceGetReleaseNotesOK{}
}

/*
VersionServiceGetReleaseNotesOK describes a response with status code 200, with default header values.

A successful response.
*/
type VersionServiceGetReleaseNotesOK struct {
	Payload *models.VersionGetReleaseNotesResponse
}

// IsSuccess returns true when this version service get release notes o k response has a 2xx status code
func (o *VersionServiceGetReleaseNotesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this version service get release notes o k response has a 3xx status code
func (o *VersionServiceGetReleaseNotesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this version service get release notes o k response has a 4xx status code
func (o *VersionServiceGetReleaseNotesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this version service get release notes o k response has a 5xx status code
func (o *VersionServiceGetReleaseNotesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this version service get release notes o k response a status code equal to that given
func (o *VersionServiceGetReleaseNotesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the version service get release notes o k response
func (o *VersionServiceGetReleaseNotesOK) Code() int {
	return 200
}

func (o *VersionServiceGetReleaseNotesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /release-notes/v1/{product}/{version}][%d] versionServiceGetReleaseNotesOK %s", 200, payload)
}

func (o *VersionServiceGetReleaseNotesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /release-notes/v1/{product}/{version}][%d] versionServiceGetReleaseNotesOK %s", 200, payload)
}

func (o *VersionServiceGetReleaseNotesOK) GetPayload() *models.VersionGetReleaseNotesResponse {
	return o.Payload
}

func (o *VersionServiceGetReleaseNotesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(models.VersionGetReleaseNotesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVersionServiceGetReleaseNotesDefault creates a VersionServiceGetReleaseNotesDefault with default headers values
func NewVersionServiceGetReleaseNotesDefault(code int) *VersionServiceGetReleaseNotesDefault {
	return &VersionServiceGetReleaseNotesDefault{
		_statusCode: code,
	}
}

/*
VersionServiceGetReleaseNotesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type VersionServiceGetReleaseNotesDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this version service get release notes default response has a 2xx status code
func (o *VersionServiceGetReleaseNotesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this version service get release notes default response has a 3xx status code
func (o *VersionServiceGetReleaseNotesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this version service get release notes default response has a 4xx status code
func (o *VersionServiceGetReleaseNotesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this version service get release notes default response has a 5xx status code
func (o *VersionServiceGetReleaseNotesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this version service get release notes default response a status code equal to that given
func (o *VersionServiceGetReleaseNotesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the version service get release notes default response
func (o *VersionServiceGetReleaseNotesDefault) Code() int {
	return o._statusCode
}

func (o *VersionServiceGetReleaseNotesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /release-notes/v1/{product}/{version}][%d] VersionService_GetReleaseNotes default %s", o._statusCode, payload)
}

func (o *VersionServiceGetReleaseNotesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /release-notes/v1/{product}/{version}][%d] VersionService_GetReleaseNotes default %s", o._statusCode, payload)
}

func (o *VersionServiceGetReleaseNotesDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *VersionServiceGetReleaseNotesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
