// Code generated by go-swagger; DO NOT EDIT.

package version_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVersionServiceMetadataV2Params creates a new VersionServiceMetadataV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVersionServiceMetadataV2Params() *VersionServiceMetadataV2Params {
	return &VersionServiceMetadataV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewVersionServiceMetadataV2ParamsWithTimeout creates a new VersionServiceMetadataV2Params object
// with the ability to set a timeout on a request.
func NewVersionServiceMetadataV2ParamsWithTimeout(timeout time.Duration) *VersionServiceMetadataV2Params {
	return &VersionServiceMetadataV2Params{
		timeout: timeout,
	}
}

// NewVersionServiceMetadataV2ParamsWithContext creates a new VersionServiceMetadataV2Params object
// with the ability to set a context for a request.
func NewVersionServiceMetadataV2ParamsWithContext(ctx context.Context) *VersionServiceMetadataV2Params {
	return &VersionServiceMetadataV2Params{
		Context: ctx,
	}
}

// NewVersionServiceMetadataV2ParamsWithHTTPClient creates a new VersionServiceMetadataV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewVersionServiceMetadataV2ParamsWithHTTPClient(client *http.Client) *VersionServiceMetadataV2Params {
	return &VersionServiceMetadataV2Params{
		HTTPClient: client,
	}
}

/*
VersionServiceMetadataV2Params contains all the parameters to send to the API endpoint

	for the version service metadata v2 operation.

	Typically these are written to a http.Request.
*/
type VersionServiceMetadataV2Params struct {

	// Product.
	Product string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the version service metadata v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceMetadataV2Params) WithDefaults() *VersionServiceMetadataV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the version service metadata v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VersionServiceMetadataV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) WithTimeout(timeout time.Duration) *VersionServiceMetadataV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) WithContext(ctx context.Context) *VersionServiceMetadataV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) WithHTTPClient(client *http.Client) *VersionServiceMetadataV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProduct adds the product to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) WithProduct(product string) *VersionServiceMetadataV2Params {
	o.SetProduct(product)
	return o
}

// SetProduct adds the product to the version service metadata v2 params
func (o *VersionServiceMetadataV2Params) SetProduct(product string) {
	o.Product = product
}

// WriteToRequest writes these params to a swagger request
func (o *VersionServiceMetadataV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param product
	if err := r.SetPathParam("product", o.Product); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
