// Code generated by go-swagger; DO NOT EDIT.

package version_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/percona/percona-xtradb-cluster-operator/pkg/version/client/models"
)

// VersionServiceMetadataReader is a Reader for the VersionServiceMetadata structure.
type VersionServiceMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionServiceMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVersionServiceMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVersionServiceMetadataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVersionServiceMetadataOK creates a VersionServiceMetadataOK with default headers values
func NewVersionServiceMetadataOK() *VersionServiceMetadataOK {
	return &VersionServiceMetadataOK{}
}

/*
VersionServiceMetadataOK describes a response with status code 200, with default header values.

A successful response.
*/
type VersionServiceMetadataOK struct {
	Payload *models.VersionMetadataResponse
}

// IsSuccess returns true when this version service metadata o k response has a 2xx status code
func (o *VersionServiceMetadataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this version service metadata o k response has a 3xx status code
func (o *VersionServiceMetadataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this version service metadata o k response has a 4xx status code
func (o *VersionServiceMetadataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this version service metadata o k response has a 5xx status code
func (o *VersionServiceMetadataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this version service metadata o k response a status code equal to that given
func (o *VersionServiceMetadataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the version service metadata o k response
func (o *VersionServiceMetadataOK) Code() int {
	return 200
}

func (o *VersionServiceMetadataOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /metadata/v1/{product}][%d] versionServiceMetadataOK %s", 200, payload)
}

func (o *VersionServiceMetadataOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /metadata/v1/{product}][%d] versionServiceMetadataOK %s", 200, payload)
}

func (o *VersionServiceMetadataOK) GetPayload() *models.VersionMetadataResponse {
	return o.Payload
}

func (o *VersionServiceMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(models.VersionMetadataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVersionServiceMetadataDefault creates a VersionServiceMetadataDefault with default headers values
func NewVersionServiceMetadataDefault(code int) *VersionServiceMetadataDefault {
	return &VersionServiceMetadataDefault{
		_statusCode: code,
	}
}

/*
VersionServiceMetadataDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type VersionServiceMetadataDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this version service metadata default response has a 2xx status code
func (o *VersionServiceMetadataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this version service metadata default response has a 3xx status code
func (o *VersionServiceMetadataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this version service metadata default response has a 4xx status code
func (o *VersionServiceMetadataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this version service metadata default response has a 5xx status code
func (o *VersionServiceMetadataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this version service metadata default response a status code equal to that given
func (o *VersionServiceMetadataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the version service metadata default response
func (o *VersionServiceMetadataDefault) Code() int {
	return o._statusCode
}

func (o *VersionServiceMetadataDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /metadata/v1/{product}][%d] VersionService_Metadata default %s", o._statusCode, payload)
}

func (o *VersionServiceMetadataDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /metadata/v1/{product}][%d] VersionService_Metadata default %s", o._statusCode, payload)
}

func (o *VersionServiceMetadataDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *VersionServiceMetadataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
