apiVersion: pxc.percona.com/v1-6-0
kind: PerconaXtraDBCluster
metadata:
  name: side-car
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    size: 3
    image: -pxc
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: "1G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  proxysql:
    enabled: true
    size: 2
    image: -proxysql
    serviceType: LoadBalancer
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
    sidecarResources:
      requests:
        memory: 1G
        cpu: 500m
      limits:
        memory: 2G
        cpu: 600m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
