apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets-2
type: Opaque
data:
  root: cm9vdF9wYXNzd29yZA==
  xtrabackup: YmFja3VwX3Bhc3N3b3Jk
  monitor: bW9uaXRvcg==
  proxyadmin: YWRtaW5fcGFzc3dvcmQ=
  pmmserver: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: user-one
type: Opaque
data:
  userOnePassKey: dGVzdHBhc3MK
---
apiVersion: v1
kind: Secret
metadata:
  name: user-two
type: Opaque
data:
  userTwoPassKey: dGVzdHBhc3MK
  password: dGVzdHBhc3MK

