apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: simple-pxc
spec:
  crVersion: 1.15.0
  secretsName: simple-dev-secrets
  unsafeFlags:
    pxcSize: true
    proxySize: true
  enableCRValidationWebhook: true

  haproxy:
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
    size: 1
    enabled: true
    replicasServiceEnabled: false

  pxc:
    image: percona/percona-xtradb-cluster:8.0
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1G
