apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: no-storage
spec:
  crVersion: 1.10.0
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  enableCRValidationWebhook: true
  pxc:
    size: 3
    image: -pxc
#    volumeSpec:
#      emptyDir: {}
#      hostPath:
#        path: /data
#        type: Directory
#      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#        requests:
#        storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
#    volumeSpec:
#      emptyDir: {}
#      hostPath:
#        path: /data
#        type: Directory
#      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#        requests:
#        storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
