apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-gcp-cs
  finalizers:
    - delete-s3-backup
spec:
  pxcCluster: demand-backup-cloud
  storageName: gcp-cs
