apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-azure-blob
  finalizers:
    - delete-azure-backup
spec:
  pxcCluster: demand-backup-cloud
  storageName: azure-blob
