apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-aws-s3
  finalizers:
    - percona.com/delete-backup
spec:
  pxcCluster: demand-backup-cloud
  storageName: aws-s3
