apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-gcp-cs
  finalizers:
    - percona.com/delete-backup
spec:
  pxcCluster: demand-backup-cloud
  storageName: gcp-cs
