apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-aws-s3
  finalizers:
    - delete-s3-backup
spec:
  pxcCluster: demand-backup-cloud
  storageName: aws-s3
