#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. "${test_dir}"/../functions
cluster="self-healing-advanced"

delete_all_pods() {
    # run chaos for Pods
    for _ in $(seq 1 5); do
        kubectl_bin delete pod self-healing-advanced-pxc-0 self-healing-advanced-pxc-1 self-healing-advanced-pxc-2 --grace-period=0 --force || :
    done

    sleep 60

    wait_for_running $cluster-pxc 3

    for i in $(seq 0 2);do
        local logs=$(kubectl_bin logs --tail=1 self-healing-advanced-pxc-$i pxc)
        if [ "${logs}" != '#####################################################FULL_PXC_CLUSTER_CRASH#####################################################' ];then
            echo "cluster not in crash"
            exit 1
        fi
    done
}

restore_after_crash(){
    cat_config "$test_dir/conf/$cluster.yml" \
        | sed -e 's/autoRecovery: false/autoRecovery: true/' \
        | kubectl_bin apply -f-
    kubectl_bin delete pod self-healing-advanced-pxc-0 self-healing-advanced-pxc-1 self-healing-advanced-pxc-2 --grace-period=0 --force || :

    wait_for_running $cluster-pxc 3
    sleep 240

    desc 'check data consistency for chaosed Pod'
    compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-0.$cluster-pxc -uroot -proot_password"
    compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-1.$cluster-pxc -uroot -proot_password"
    compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-2.$cluster-pxc -uroot -proot_password"
}

main() {
    create_infra $namespace

    kubectl_bin apply -f "$test_dir/conf/pumba.yml"

    desc 'start cluster'
    spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

    desc 'delete all PXC pods and check full crash'
    delete_all_pods

    desc 'repair full cluster crash'
    restore_after_crash

    destroy "$namespace"
}

main