apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: restore-on-pitr-minio-time
spec:
  pxcCluster: pitr
  backupName: on-pitr-minio
  pitr:
    type: date
    date: "<datetime>"
    backupSource:
      storageName: "minio-binlogs"

