apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  annotations:
    percona.com/unsafe-pitr: "true"
  name: on-pitr-minio-invalid
spec:
  pxcCluster: pitr
  backupName: on-pitr-minio-invalid 
  pitr:
    type: transaction
    gtid: <gtid>
    backupSource:
      storageName: "minio-binlogs"
