apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-pitr-minio-gap-error
spec:
  pxcCluster: pitr
  backupName: on-pitr-minio-gap
  pitr:
    type: latest
    backupSource:
      storageName: "minio-binlogs"
