apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-pitr-minio
spec:
  pxcCluster: pitr
  backupName: on-pitr-minio
  pitr:
    type: transaction
    gtid: <gtid>
    backupSource:
      storageName: "minio-binlogs"

