apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-pitr-minio
spec:
  pxcCluster: pitr
  backupSource:
    verifyTLS: false
    destination: <destination>
    s3:
      bucket: operator-testing
      credentialsSecret: minio-secret
      endpointUrl: https://minio-service.#namespace:9000/
      region: us-east-1
  pitr:
    type: latest
    backupSource:
      verifyTLS: false
      s3:
        bucket: operator-testing/binlogs
        credentialsSecret: minio-secret
        endpointUrl: https://minio-service.#namespace:9000/
        region: us-east-1

