apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/name: percona-xtradb-cluster
  name: some-name-pxc
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: some-name
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: mysql-admin
      port: 33062
      protocol: TCP
      targetPort: 33062
  selector:
    app.kubernetes.io/component: pxc
    app.kubernetes.io/instance: some-name
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: ClusterIP
