apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-minio
  finalizers:
    - delete-s3-backup
spec:
  pxcCluster: demand-backup
  storageName: minio
  containerOptions:
    args:
      xbstream: 
      - '--parallel=2'
      xbcloud: 
      - '--parallel=2'
      - '--curl-retriable-errors=8'
