apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-minio
  finalizers:
    - delete-s3-backup
spec:
  pxcCluster: demand-backup
  storageName: minio
  resources:
    requests:
      memory: 0.5G
      cpu: 500m
    limits:
      memory: "2G"
      cpu: "1"
