apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: on-demand-backup-minio
  finalizers:
    - percona.com/delete-backup
spec:
  pxcCluster: demand-backup
  storageName: minio
  activeDeadlineSeconds: 7200
  containerOptions:
    args:
      xbstream: 
      - '--parallel=2'
      xbcloud: 
      - '--parallel=2'
      - '--curl-retriable-errors=8'
