apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-demand-backup-pvc-bsource
spec:
  pxcCluster: demand-backup
  backupSource:
    destination: pvc/xb-on-demand-backup-pvc-bsource
    storageName: pvc
  resources:
    requests:
      memory: 0.5G
      cpu: 500m
    limits:
      memory: "1G"
      cpu: "2"
