apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-demand-backup-pvc
spec:
  pxcCluster: demand-backup
  backupName: on-demand-backup-pvc
  resources:
    requests:
      memory: 0.5G
      cpu: 500m
    limits:
      memory: "3G"
      cpu: "2"
