apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: "no-proxysql"
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/pxc-openshift:0.2.0
    configuration: |
      [mysqld]
      wsrep_debug=ON
      [sst]
      wsrep_debug=ON
    resources:
      requests:
        memory: 10M
        cpu: 100m
    volumeSpec:
      accessModes: [ "ReadWriteOnce" ]
      size: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: false
    size: 1
    image: perconalab/proxysql-openshift:0.2.0
    resources:
      requests:
        memory: 10M
        cpu: 100m
    volumeSpec:
      accessModes: [ "ReadWriteOnce" ]
      size: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.0
    serverHost: monitoring-service
    serverUser: pmm
