---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-percona-xtradb-cluster-operator
subjects:
  - kind: ServiceAccount
    name: percona-xtradb-cluster-operator
    namespace: "pxc-operator"
roleRef:
  kind: ClusterRole
  name: percona-xtradb-cluster-operator
  apiGroup: rbac.authorization.k8s.io
