apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    backup-name: on-demand-backup-azure-blob
    cluster: demand-backup-cloud
    job-name: xb-on-demand-backup-azure-blob
    type: xtrabackup
  name: xb-on-demand-backup-azure-blob
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterBackup
      name: on-demand-backup-azure-blob
spec:
  backoffLimit: 10
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      backup-name: on-demand-backup-azure-blob
      cluster: demand-backup-cloud
      job-name: xb-on-demand-backup-azure-blob
      type: xtrabackup
  suspend: false
  template:
    metadata:
      labels:
        backup-name: on-demand-backup-azure-blob
        cluster: demand-backup-cloud
        job-name: xb-on-demand-backup-azure-blob
        type: xtrabackup
    spec:
      containers:
        - command:
            - bash
            - /usr/bin/backup.sh
          env:
            - name: BACKUP_DIR
              value: /backup
            - name: PXC_SERVICE
              value: demand-backup-cloud-pxc
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "true"
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_NAME
                  name: azure-secret
            - name: AZURE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_KEY
                  name: azure-secret
            - name: AZURE_ENDPOINT
            - name: AZURE_STORAGE_CLASS
              value: Cool
          imagePullPolicy: Always
          name: xtrabackup
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/mysql/ssl
              name: ssl
            - mountPath: /etc/mysql/ssl-internal
              name: ssl-internal
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
          - 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ssl
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-cloud-ssl
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-cloud-ssl-internal
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
