apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: demand-backup-cloud
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
    percona.com/backup-job-name: xb-on-demand-backup-azure-blob
    percona.com/backup-name: on-demand-backup-azure-blob
    percona.com/backup-type: xtrabackup
    percona.com/cluster: demand-backup-cloud
  name: xb-on-demand-backup-azure-blob
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterBackup
      name: on-demand-backup-azure-blob
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      app.kubernetes.io/instance: demand-backup-cloud
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
      percona.com/backup-job-name: xb-on-demand-backup-azure-blob
      percona.com/backup-name: on-demand-backup-azure-blob
      percona.com/backup-type: xtrabackup
      percona.com/cluster: demand-backup-cloud
  suspend: false
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demand-backup-cloud
        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
        percona.com/backup-job-name: xb-on-demand-backup-azure-blob
        percona.com/backup-name: on-demand-backup-azure-blob
        percona.com/backup-type: xtrabackup
        percona.com/cluster: demand-backup-cloud
    spec:
      containers:
        - command:
            - /opt/percona/xtrabackup-run-backup
          env:
            - name: HOST
              value: demand-backup-cloud-pxc-0.demand-backup-cloud-pxc.namespace.svc.cluster.local
            - name: STORAGE_TYPE
              value: azure
            - name: VERIFY_TLS
              value: "true"
            - name: BACKUP_NAME
              value: on-demand-backup-azure-blob
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_NAME
                  name: azure-secret
            - name: AZURE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_KEY
                  name: azure-secret
            - name: AZURE_ENDPOINT
            - name: AZURE_STORAGE_CLASS
              value: Cool
            - name: BACKUP_DEST
              value: demand-backup-cloud-2025-12-04-16:25:39-full
          imagePullPolicy: Always
          name: xtrabackup
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
            - mountPath: /etc/mysql/ssl
              name: ssl
            - mountPath: /etc/mysql/ssl-internal
              name: ssl-internal
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /backup-init-entrypoint.sh
          imagePullPolicy: Always
          name: backup-init
          resources:
            limits:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/percona
              name: bin
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: bin
        - name: ssl
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-cloud-ssl
        - name: ssl-internal
          secret:
            defaultMode: 420
            optional: true
            secretName: demand-backup-cloud-ssl-internal
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
