apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    batch.kubernetes.io/job-name: restore-job-on-demand-backup-s3-demand-backup-cloud
    job-name: restore-job-on-demand-backup-s3-demand-backup-cloud
  name: restore-job-on-demand-backup-s3-demand-backup-cloud
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBClusterRestore
      name: on-demand-backup-s3
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels: {}
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: restore-job-on-demand-backup-s3-demand-backup-cloud
        job-name: restore-job-on-demand-backup-s3-demand-backup-cloud
    spec:
      containers:
        - command:
            - recovery-cloud.sh
          env:
            - name: PXC_SERVICE
              value: demand-backup-cloud-pxc
            - name: PXC_USER
              value: xtrabackup
            - name: PXC_PASS
              valueFrom:
                secretKeyRef:
                  key: xtrabackup
                  name: my-cluster-secrets
            - name: VERIFY_TLS
              value: "true"
            - name: ENDPOINT
            - name: DEFAULT_REGION
              value: us-east-1
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: aws-s3-secret
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: aws-s3-secret
            - name: XBCLOUD_EXTRA_ARGS
              value: --parallel=2
            - name: XBSTREAM_EXTRA_ARGS
              value: --parallel=2
            - name: XB_USE_MEMORY
              value: 100MB
          imagePullPolicy: Always
          name: xtrabackup
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /datadir
              name: datadir
            - mountPath: /etc/mysql/vault-keyring-secret
              name: vault-keyring-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-demand-backup-cloud-pxc-0
        - name: vault-keyring-secret
          secret:
            defaultMode: 420
            optional: true
            secretName: some-name-vault
