#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

main() {
	create_infra $namespace
	start_minio

	cluster="demand-backup"
	spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

	run_backup "$cluster" "on-demand-backup-pvc"
	run_recovery_check "$cluster" "on-demand-backup-pvc"
	check_pvc_md5

	run_backup "$cluster" "on-demand-backup-pvc-bsource"
	run_recovery_check "$cluster" "on-demand-backup-pvc-bsource"

	run_backup "$cluster" "on-demand-backup-minio"
	run_recovery_check "$cluster" "on-demand-backup-minio"

	destroy $namespace
}

main
