#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

check_finalizer_for_fs() {
	local backup_name="$1"
	local finalizer_flag="off"

	desc "Checking finalizers on backup $backup_name"
	# Check if pxc-backup has the finalizer "percona.com/delete-backup"
	if kubectl get pxc-backup "$backup_name" -o jsonpath='{.metadata.finalizers}' | grep -q "percona.com/delete-backup"; then
		finalizer_flag="on"
	fi

	echo "Finalizer is $finalizer_flag"

	echo "Looking for PVCs containing '$backup_name'"
	pvc=$(kubectl get pvc --no-headers -o custom-columns=":metadata.name" | grep "$backup_name")

	if [[ -z $pvc ]]; then
		echo "No PVCs found with substring '$backup_name' before the backup deletion. Something wrong with backup"
		return 1
	fi

	echo "Deleting backup $backup_name ..."
	kubectl delete pxc-backup "$backup_name"
	kubectl wait --for=delete pxc-backup/"$backup_name" --timeout=30s || true

	pvc=$(kubectl get pvc --no-headers -o custom-columns=":metadata.name" | grep "$backup_name" || true)

	echo "Checking PVC $pvc existence and finalizers"

	if [[ -z $pvc && $finalizer_flag == "off" ]]; then
		echo "Error: No PVCs found with substring '$backup_name'. PVC was deleted even though finalizer is OFF."
		exit 1

	elif [[ -z $pvc && $finalizer_flag == "on" ]]; then
		echo "Correct: No PVCs found with substring '$backup_name' because finalizer is ON and PVC was deleted."

	elif [[ -n $pvc && $finalizer_flag == "on" ]]; then
		echo "Error: PVC exists: $pvc (finalizer_flag=$finalizer_flag). Finalizer should delete PVC but did NOT."
		exit 1

	else
		echo "PVC exists: $pvc (finalizer_flag=$finalizer_flag)"
	fi

}

main() {
	create_infra $namespace

	cluster="demand-backup"
	spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"

	run_backup "$cluster" "on-demand-backup-pvc"
	run_recovery_check "$cluster" "on-demand-backup-pvc"
	compare_kubectl job/restore-job-on-demand-backup-pvc-demand-backup

	check_pvc_md5 "on-demand-backup-pvc"
	check_finalizer_for_fs "on-demand-backup-pvc"

	run_backup "$cluster" "on-demand-backup-pvc-with-finalizer"
	check_finalizer_for_fs "on-demand-backup-pvc-with-finalizer"

	run_backup "$cluster" "on-demand-backup-pvc-bsource"
	run_recovery_check "$cluster" "on-demand-backup-pvc-bsource"
	compare_kubectl job/restore-job-on-demand-backup-pvc-bsource-demand-backup

	destroy $namespace
	desc "test passed"
}

main
