apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
