apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: some-name
  finalizers:
    - percona.com/delete-proxysql-pvc
    - percona.com/delete-pxc-pvc
  # annotations:
  #   percona.com/issue-vault-token: "true"
spec:
  secretsName: my-cluster-secrets
  vaultSecretName: some-name-vault
  pause: false
  pxc:
    size: 3
    image: -pxc
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: "2G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: gp2-resizable
        resources:
          requests:
            storage: 3Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  haproxy:
    enabled: true
    size: 2
    image: -haproxy
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: 1G
        cpu: 700m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  logcollector:
    enabled: true
    image: -logcollector
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
  backup:
    image: -backup
    storages:
      pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1G
      aws-s3:
        type: s3
        s3:
          region: us-east-1
          bucket: operator-testing
          credentialsSecret: aws-s3-secret
      minio:
        type: s3
        s3:
          credentialsSecret: minio-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: http://minio-service:9000/
      gcp-cs:
        type: s3
        s3:
          credentialsSecret: gcp-cs-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: https://storage.googleapis.com
