// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VersionMetadataV2Version MetadataV2Version represents metadata for a given version with additional fields.
//
// swagger:model versionMetadataV2Version
type VersionMetadataV2Version struct {

	// ImageInfo holds information about the docker image for this version.
	ImageInfo *VersionVersionV2 `json:"imageInfo,omitempty"`

	// Recommended is the recommended version for a given component.
	Recommended map[string]string `json:"recommended,omitempty"`

	// Supported holds semver constraint per component, such as ">= 1.0, < 1.4".
	Supported map[string]string `json:"supported,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this version metadata v2 version
func (m *VersionMetadataV2Version) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImageInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionMetadataV2Version) validateImageInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.ImageInfo) { // not required
		return nil
	}

	if m.ImageInfo != nil {
		if err := m.ImageInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageInfo")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this version metadata v2 version based on the context it is used
func (m *VersionMetadataV2Version) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateImageInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VersionMetadataV2Version) contextValidateImageInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.ImageInfo != nil {

		if swag.IsZero(m.ImageInfo) { // not required
			return nil
		}

		if err := m.ImageInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("imageInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("imageInfo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionMetadataV2Version) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionMetadataV2Version) UnmarshalBinary(b []byte) error {
	var res VersionMetadataV2Version
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
