#!/bin/bash

set -o errexit

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

set_debug

run_recovery_check() {
	local cluster=$1
	local backup1=$2

	restore_name="${backup1:22:32}"

	desc 'write data after backup'
	run_mysql \
		'INSERT myApp.myApp (id) VALUES (100501)' \
		"-h $cluster-proxysql -uroot -proot_password"

	for node in \
		"$cluster-pxc-0.$cluster-pxc" \
		"$cluster-pxc-1.$cluster-pxc" \
		"$cluster-pxc-2.$cluster-pxc"; do
		local retry=0
		until [[ "$(run_mysql 'SELECT COUNT(*) FROM myApp.myApp;' \
			"-h $node -uroot -proot_password" 2>/dev/null)" == "2" ]]; do
			[ $retry -ge 12 ] && echo "Row not propagated to $node after 1 min" && exit 1
			sleep 5
			retry=$((retry + 1))
		done
	done
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-0.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-1.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-2" "SELECT * from myApp.myApp;" "-h $cluster-pxc-2.$cluster-pxc -uroot -proot_password"

	desc 'recover backup'
	cat $src_dir/deploy/backup/restore.yaml \
		| $sed "s/pxcCluster: .*/pxcCluster: $cluster/" \
		| $sed "s/backupName: .*/backupName: $backup1/" \
		| $sed "s/name: .*/name: $restore_name/" \
		| kubectl_bin apply -f -
	wait_backup_restore ${restore_name}

	kubectl_bin logs job/restore-job-${restore_name}-${cluster:0:16}

	wait_for_running "$cluster-proxysql" 1
	wait_for_running "$cluster-pxc" 3

	for node in "$cluster-pxc-0.$cluster-pxc" "$cluster-pxc-1.$cluster-pxc" "$cluster-pxc-2.$cluster-pxc"; do
		local retry=0
		until run_mysql 'SELECT 1;' "-h $node -uroot -proot_password" 2>/dev/null | grep -q 1; do
			[ $retry -ge 24 ] && echo "Node $node not accessible after 2 min" && exit 1
			sleep 5
			retry=$((retry + 1))
		done
	done

	desc 'check data after backup'
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-0.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-1.$cluster-pxc -uroot -proot_password"
	compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-2.$cluster-pxc -uroot -proot_password"
}

get_backup_name() {
	kubectl_bin get pxc-backup -o=jsonpath='{range .items[*]}{.metadata.name}{":"}{.spec.storageName}{":"}{.status.state}{"\n"}{end}' \
		| grep ":$1:Succeeded" \
		| tail -1 \
		| cut -d ':' -f 1
}

main() {
	create_infra $namespace
	start_minio

	cluster="scheduled-backup"

	cat - <<-EOF | kubectl_bin apply -f -
		        apiVersion: scheduling.k8s.io/v1
		        kind: PriorityClass
		        metadata:
		            name: high-priority
		        value: 1000000
		        globalDefault: false
		        description: "This priority class should be used for backup service pods only."
	EOF

	spinup_pxc "$cluster" "$test_dir/conf/${cluster}-init.yml"

	desc 'add backups schedule for pvc storage'
	kubectl_bin config set-context "$(kubectl_bin config current-context)" --namespace="$namespace"
	apply_config "${test_dir}/conf/${cluster}-pvc.yml"
	label_node
	wait_first_backup_appears "pvc"
	apply_config "${test_dir}/conf/${cluster}-disable.yml"
	wait_all_backups
	desc 'add backups schedule for minio storage'
	apply_config "${test_dir}/conf/${cluster}-minio.yml"
	wait_first_backup_appears "minio"
	apply_config "${test_dir}/conf/${cluster}-disable.yml"
	wait_all_backups

	backup_name_pvc=$(get_backup_name "pvc")
	backup_name_minio=$(get_backup_name "minio")

	apply_config "$test_dir/conf/${cluster}-init.yml"

	run_recovery_check "$cluster" "$backup_name_pvc"
	run_recovery_check "$cluster" "$backup_name_minio"

	unlabel_node
	destroy $namespace
	desc "test passed"
}

main
