#!/bin/bash

set -o errexit
set -o xtrace

test_dir=$(realpath $(dirname $0))
. ${test_dir}/../functions

main() {
  create_infra $namespace
  cluster="some-name"

  desc 'deploy cert manager'
  deploy_cert_manager

  sleep 30

  desc 'create pxc cluster'
  spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml" 3 10 'secrets_without_tls.yml'

  desc 'check if certificates issued with certmanager'
  tlsSecretsShouldExist

  desc 'check if default issuer created'
  compare_kubectl issuer/$cluster-pxc-ca

  desc 'check if certificate issued'
  compare_kubectl certificate/$cluster-ssl

  destroy $namespace
}

main
