apiVersion: pxc.percona.com/v1-2-0
kind: PerconaXtraDBCluster
metadata:
  name: sec-context
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    annotations:
      openshift.io/scc: privileged
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      runAsUser: 1001
      fsGroup: 1001
    size: 3
    image: -pxc
    serviceAccountName: percona-xtradb-cluster-operator-workload
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: "1G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  proxysql:
    enabled: true
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      runAsUser: 1001
      fsGroup: 1001
    size: 1
    image: -proxysql
    serviceAccountName: percona-xtradb-cluster-operator-workload
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none

